mathematicalthinking/vmt

client/src/Containers/Workspace/GgbGraph.js, client/src/Containers/Workspace/Workspace.js
* When a user was interacting with a geogebra construction and they lost connection the app would crash because control was not being released at the appropriate time...i.e. after connection was lost but before any manipulation to the construction could be done. This [video](https://drive.google.com/open?id=1JjTaJn_bIqeNHZO5HitaxtMeeM3z9MFH) shows the bug. 
* This bug originated in the `toggleControl` method of containers/workspace the first thing we were doing was checking if the user was connected and if not we returned an alert. This had the effect of skipping the functionality that actually releases control. To fix we've added two place alerts can happen (at the beginning like before if toggling control was triggered manually by the user...In that case we DONT want to update the …
=> Fix crash on disconnect

config/passport.js, controllers/RoomController.js
previous pr created problems for assigning activity to room. Sometimes tabs were populated other times they were not. this may be worth revisiting at some point because now we're over fetching...but by populating all of the users activities' tabs on login we solve this problem. When a room is created from an activity the tabs are always populated...
...I think what we should ultimately do is just send the tab ids with the post request regardless of their population status.
=> populate all activity tabs

client/src/Components/HOC/SocketProvider.js, client/src/store/actions/user.js, controllers/ActivityController.js, controllers/RoomController.js
* When a user makes a room or activity from an existing activity it was mutating that activities tabs instead of copying and creating new tabs.
* On Socket reconnect user object in store was getting populated resources instead of just ids
closes #125
=> Fix mutation of tabs

client/src/Components/HOC/SocketProvider.js
#173 was missing a fetchUser call on SocketProvide componentDidMount(); 
If the user is already logged in (because their session hasnt expired) when they arrive at vmt, we might not have their most recent notification so we should fetch the user every time a logged in user lands on the homepage.
=> fetch user on appLoad

client/src/Containers/Replayer/EncompassReplayer.js, client/src/Containers/Replayer/SharedReplayer.js
Add optional arguments doAutoPlay and stopTime to goToTime function
When Encompass user clicks on a vmt selection in encompass, a message will be sent to vmt instructing vmt to invoke goToTime with doAutoPlay=true and stopTime equal to the vmt selection's end time.
This way the replayer will immediately start replaying the selected selection and automatically stop when the end is reached
=> Optional auto play and forced stop time for goToTime function

client/src/Containers/Workspace/GgbGraph.js
Issue still exists zooming in when roots tool is active, This causes points to be dynamically deleted. If the user is not in control this throws a warning. We want to avoid this warning but make sure the warning still occurs for true deletion events
=> Ggb xml transfer

client/src/Components/Chat/Chat.js, client/src/Components/Navigation/HomeNav/HomeNav.js, client/src/Components/Navigation/NavItem/NavItem.js, client/src/Containers/Create/NewTabForm.js, client/src/Containers/Replayer/GgbReplayer.js, client/src/Containers/Workspace/ActivityWorkspace.js, client/src/Containers/Workspace/ControlWarningModal.js, client/src/Containers/Workspace/GgbActivityGraph.js, client/src/Containers/Workspace/GgbGraph.js, client/src/Containers/Workspace/Tools/ActivityTools.js, client/src/Containers/Workspace/Tools/Awareness.js, client/src/Containers/Workspace/Tools/GgbIcons/index.js, client/src/Containers/Workspace/Tools/Tools.js, client/src/Containers/Workspace/ggbUtils.js, client/src/Layout/Facilitator/Facilitator.js, client/src/Layout/Homepage/Homepage.js, client/src/Layout/Workspace/Workspace.js, client/src/utils/sockets.js, server/controllers/ActivityController.js, server/controllers/CourseController.js, server/controllers/RoomController.js, server/cypress/integration/admin.js, server/cypress/integration/create.js, server/cypress/integration/workspace.js, server/models/Event.js, server/models/Message.js, server/models/Tab.js
Refactored to storing state of geogebra rooms using base64
- prevents loss of additional files/images uploaded into room
Reenabled Undo/Redo for geogebra rooms
Use zoom tool for referencing in geogebra rooms instead of move tool 
- now users who are not in control cannot move things around, even if they are referencing
Now emitting "changePerspective" events when users change perspectives, such as adding a 2nd graph or switching to spreadsheet mode"
- could potentially add a more detailed description of which views were added or removed
Referencing works with multiple graphs visible 
- There are still issues when emitting objects with multiple graphs visible 
- The object may show up on wrong graph, but if the room is reloaded the object will be on the correct graph 
Various fixes to …
=> Storing state of rooms with base64

client/src/Containers/Workspace/Workspace.js
fixes #288 
The render function for the Workspace Component (in client/src/Containers/Workspace.js) was resetting the focus of the page to an input field in the "create an activity" modal window every time it was called. 
This was causing the Desmos calculator to lose focus every time the user in control of the room made a change to the equation. Every change triggers the Workspace function `addToLog`, which updates the state, which triggers a re-render.
Now Workspace will only change the focus of the page if the state variable `isCreatingActivity` is true.
=> Keep Focus When Entering Equation in Desmos Tab

server/config/app-urls.js
Related to this [thread](https://mathematicalt-8xw5409.slack.com/archives/CL08R6U67/p1602780697000400?thread_ts=1602687668.011800&cid=CL08R6U67).
Issue:
Previous ENV variable changes to production server of enc and vmt caused a CORS error when importing vmt workspaces from encompass.
PR Fix:
Change will hardcode the correct encompass production url.
=> [Bug]Fix production ENC url

client/src/Components/UI/Backdrop/Backdrop.js, client/src/Containers/Members/ImportModal.js, client/src/Containers/Members/Members.js, client/src/Layout/ClassCode/ClassCode.js, client/src/utils/validators.js
* Created facility to handle both new and existing users when importing from a file. If the username and email are both from the same existing user, that user is invited to the course. If there is a mismatch between the username and email (e.g., existing username but with a different email or vice versa), buttons are presented that allow the user to resolve the mismatch.
* If a user edits a cell of the table, that row is checked for validation errors.
* Cleaned up some propType errors
=> Handle existing users on import

client/src/Components/CurrentMembers/CurrentMembers.js, client/src/Components/UI/ToggleGroup/toggleGroup.css, client/src/Containers/Course.js, client/src/Containers/Monitoring/MonitoringView.js, server/models/Course.js
Added new option to Monitoring that allows users to see who is currently in all the rooms being monitored. The "attendance" view shows all members of each room (reusing the "Currently in Room" component); members currently in the room are bolded.  As with other monitoring views, this new view is live -- it updates every 10 sec to show who is or isn't in the room. It also updates if a new member is added or a member is deleted.
This PR also includes a possible fix to allow imported members to appear without refreshing the screen, but still allow non-owning course facilitators to see all resources in a course (previously the latter fix had caused the former bug).
=> :tada: Attendance facility for monitoring

client/src/Components/HOC/socketProvider.utils.js, client/src/Containers/Members/Members.js
* Sometimes when a new person joins a group, the notification message cannot find the resource name. Instead of crashing, the notification will now show the name as "name not found". Cannot yet replicate the error, so haven't yet tracked down root cause of the problem.
* When importing, the resolution buttons (if a mismatch between existing username and email) now reset if the user fixes the mismatch.
=> :bug: missing ntf name handled; fix for import resolution

client/src/Containers/Monitoring/SelectionTable.js, server/controllers/RoomController.js
Adds two columns to the selection table in monitoring: course name (if any) for a room and the name of the template from which the room was generated (if any). As with other columns in this table, clicking on the column label sorts the table by that column.
=> Added course and template names to monitor table

server/cypress/integration/createRoom.js, server/models/Room.js
This PR fixes the bug whereby when a user creates a room it appears twice in the resource list. At the same time, the user gets a notification about the room as if they were invited raters than they had created it. 
This PR includes the fix as well as a Cypress integration test suite (which was written first, of course).
=> Double room bug

client/src/Components/Importer/Importer.js
When importing, the column headings in the CSV do not depend on case any longer. For example, in the CSV file, the header for the column of first names may be written as Firstname, firstname, FIRSTNAME, etc., and the data will be imported to the firstName field correctly.
=> Import headings are now case insensitive

server/models/Event.js, server/models/Message.js
This PR fixes a looooong-standing bug whereby messages and events receive the wrong timestamp if a user's clock is incorrect. As a result, the replayer would present events and messages in an order different than how they actually occurred.
=> :clock130: Use server time jic client time wrong

client/src/Components/UI/Button/Button.js, client/src/Containers/Workspace/Tools/Tools.js, server/cypress/integration/workspace.js
Requested feature: When a user requests control, they may not do so again for one minute. If control changes during that minute, the button resets as appropriate.
=> Prevent spamming of RequestControl button

client/README.md, client/config/webpack.config.encompassProd.js, client/config/webpack.config.prod.js, client/package-lock.json, client/package.json
This PR upgrades from sw-precache-webpack-plugin (no longer supported) to workbox-webpack-plugin v4.x.  We cannot upgrade to the current workbox version until we upgrade webpack past 3.x.  Also removed react-dnd from package.json because it is not currently used.
=> Upgrade service worker

deploy.sh
* The package-lock.json file is now copied to the server folder
* When deploying for production, the main folder is 'current'; 'vmt' otherwise
* When deploying for production, the zip file is now encrypted.
=> convenience changes to build and deploy script

client/src/Containers/Workspace/Workspace.js
Fixes bug whereby an admin leaving a room generated "VMTBot: undefined left the room". That no longer happens.
=> Check for admin mode on leaving room

client/config/webpack.config.prod.js
When we deploy a new version of VMT, users' browsers will automatically load the new version within a few seconds (i.e., no browser refresh needed).
=> :tada: VMT automatically reloads if a new deployment

client/src/Containers/Workspace/DesmosActivity.js, client/src/Containers/Workspace/graph.css
This PR implements a new approach to preventing students from interacting with a Desmos Activity when they are not in control. This new approach captures ALL clicks, even on 'Try it', 'Check My Work', 'Reset', and animation play buttons that had previously allowed students to click on them.
We also allow for a possible scrollbar -- so that the student can scroll the DesmosActivity (vertically) without having control.
=> :tada: new approach to stop clicks if not in control

client/.env.example, client/src/Layout/ClassCode/ClassCode.js, client/src/store/actions/user.js, client/src/utils/auth.js, server/.env.example, server/routes/auth.js
In an effort to reduce the need for Client environment variables, which is needed as we moved to Docker, this PR changes the handling of 'default password' (used when students login without a password via a course code) from client-side code to server-side code.  Users should not see any difference in system behavior.
=> :tada: default passwords now handled on server side

client/src/Layout/Dashboard/MainContent/ResourceList.js, client/src/utils/utilityHooks.js
This PR implements the following fixes to sorting resources:
1. Alphabetized sorting is no longer case-sensitive
2. The Select options are no longer searchable
=> Resource Sort fixes

client/src/Components/Navigation/Navbar.js, client/src/Components/Navigation/dropdownNavItem.css, client/src/Components/Navigation/navbar.css
This PR addresses a bug whereby parts of the Desmos Activity editor preview was hidden behind the VMT navigation bar. To accommodate the editor preview, which takes up the entire screen, the VMT navigation bar has been made smaller (shorter and slightly narrower). 
This change to the navigation bar appears any time the user edits a template. At some time in the future, it should be changed to appear only if a Desmos Activity is being edited.
=> :tada: Template editor gets smaller navbar to accommodate preview

client/src/Components/ToolTip/toolTip.css, client/src/Components/UI/ContentBox/ContentBox.js, client/src/Components/UI/ContentBox/Icons/Icons.js, client/src/Components/UI/ContentBox/contentBox.css, client/src/Containers/Activity.js, client/src/Containers/RoomLobby.js, client/src/Layout/Dashboard/SidePanel/sidePanel.css, client/src/utils/getResourceTabTypes.js
This PR allows users to view the types of tabs in a given room or template. 
UI changes include the following:
- SidePanel adjustments to shrink the space invader image to allow the Enter & Replayer buttons to be viewed w/o scrolling
- Center resource name text
- If a resource has multiple tabs, "Tab Types" is displayed, else "Tab Type" is displayed
- Tab Types shown in Tool TIps (hover over room-type icon)
=> Tab Types displayed throughout VMT, Side Panel css changes

client/src/Components/Chat/Chat.js, client/src/Containers/Workspace/Workspace.js
Fixed bug where switching admin mode when in a room would incorrectly notify others of the admin or would leave "zombie" room members.
=> :bug: fixed members & messages errors on admin mode switch

client/src/Containers/Activity.js, client/src/Containers/Create/MakeRooms/AssignRooms.js, client/src/Containers/Create/MakeRooms/AssignmentMatrix.js, client/src/Containers/Create/MakeRooms/MakeRooms.js, client/src/Containers/Create/MakeRooms/makeRooms.css, client/src/Containers/Create/MakeRooms/selectAssignment.css
This PR improves some functionality when creating new user groups for a template:
- adding participants automatically adjusts the number of rooms appropriately
- tooltips have been added for alias usernames, add participants, create groupings, and edit assignments
- after selecting a previous grouping, if you select New Grouping, it now clears the assignments
=> Assign groups update

client/src/Containers/Workspace/Workspace.js
Fixes a bug whereby the room details page (number of people in a room, number of tabs, number of messages) did not update after leaving a room. (A browser refresh would be needed.) Now the page updates with the correct information when the user leaves the room. 
Note: Room details is not "live" in the sense that it does not show updates based on other users that might still be in the room.
=> Update room details when leave a room

client/package.json, client/src/Layout/Dashboard/MainContent/ResourceList.js
This pr is a temporary patch that allows users to see single resources, whereas before they only saw resources if there was more than 1.
=> Update to ResourceList to display 1+ resources instead of 2+

client/src/Containers/Stats/stats.utils.js
This pr adds backwards compatibility for Course Stats to handle messages without users.
=> In Course Stats, handle messages w/o users (old style)

client/src/Containers/Stats/CourseStats.js
In CourseStats component, ensure messages have a user before extracting the message's user._id. This handles older cases where some messages do not have users.
=> Ensure messages have users before extracting userIds

client/src/Components/Importer/Importer.js, client/src/Containers/Course.js
When importing an existing user, the isGmail flag may be updated (previously, only sponsor, institution, and identifier were updated). Additionally, the updated existing user no longer appears doubled in the course member list.
=> Adjustments to re-import

client/src/Routes/MyVmt.js
Reverts mathematicalthinking/vmt#576
The PrivateRoute authed prop needs to be configured to accept actuallyLoggedIn if not running on localhost, and logged in if running in localhost.
=> Revert "actuallyLogged in MyVMT routes uses cookies rather than store"

client/src/Containers/Data/withPopulatedRoom.js, server/sockets.js
For whatever reason (networking glitches, etc.), occasionally a user would get into a state where they would be able to interact with a room, but they would not appear in the "Current Members" list. This happened because their socketId was not being recorded in the DB. This PR does the following:
* When the user enters a room, the system ensures that their socketId is recorded in the DB
* If a user finds that they are in this state (which shouldn't happen anymore because of the point above), selecting "Force Sync" will also fix the problem.
* Also included are some enhancements to server-side error messages surrounding this issue.
=> :tada: Detect if userid-socketid aren't connected in the database

client/src/Components/Chat/SimpleChat.js, client/src/Containers/Monitoring/RoomViewer.js, client/src/Containers/Monitoring/roomViewer.css
Switching between detailed and simple chat now works again in the monitors (general monitoring, course preview, etc.). For the room previewer, switching between detailed and simple chat now uses a similar UI as in a room.
=> Fix the chat for monitors (detail/simple)

client/src/Components/Importer/Importer.js, client/src/Components/Importer/dataValidation.js
This PR changes the way that import validation works:
* If either the username or email (but not both) is for an existing user, the correct email or username is filled in.
* If the username and email indicate different existing users, the additional information is provided in the comments.
* The system no longer validates the structure or length of usernames or emails.
* Duplicate usernames or emails across rows are checked for before any other validation is done.
=> Enhanced validation for email-username on import

client/src/Containers/Workspace/ControlWarningModal.js
Made control warning modal message more generic. The 'call to action' is implied by the text of the highlighted button.
=> adjust control warning message

client/src/Containers/Archive.js, client/src/Layout/Archive/Archive.js, client/src/Layout/Dashboard/MainContent/ResourceList.js, client/src/store/actions/index.js, client/src/store/actions/rooms.js, client/src/utils/apiRequests.js, server/middleware/utils/request.js, server/routes/api.js
User's archived room ids are now generated from the back end as opposed to being passed in the headers from the front end. This enables a far greater number of archived ids to be passed from the BE to the FE.
Various bug fixes
=> Refactor archive to pull ids from backend

client/src/App.js, client/src/Components/GeneralModal.js, client/src/Components/index.js, client/src/Containers/Create/MakeRooms/MakeRooms.js, client/src/utils/utilityHooks.js
This PR addresses the long-standing issue of how we deal with modals.
Previously, we had to create somewhat hacky, bespoke modals on a case-by-case basis.
Now, we are able to use an app-level modal that can be consumed in standard way throughout the app.
Currently, this app-level modal is unused. The intention is to transition any current and future modals to use this.
=> App level modal

client/src/Components/ToolTip/toolTip.css
This PR allows the entire enter button to be shown
=> Tooltip Container overflow:hidden cut off the room lobby enter button

client/src/Containers/Monitoring/Thumbnails.js
Currently, when a user monitors a room (either via general monitoring, course preview, template preview, or room preview), the thumbnail tab will show the most recently updated thumbnail/screen snapshot. However, if there are multiple tabs or Desmos activity screens, the pull-down menu didn't display which tab/screen that most recent thumbnail is from.
This PR fixes that error. Whatever thumbnail is being shown is now reflected in the pull down menu.
(Note: Because the line endings changed from CRLF to LF, it looks like the entire file changed.)
=> Thumbnail defaults

server/controllers/RoomController.js
On the servers (test, staging, prod), Mongo does not reliably return a default value for non-existing fields in a document. This change accounts for that behavior. Really, though, either we need to fix Mongo or change every record in the DB such that it has our new status field with the correct value, which might be 'trashed', 'archived', or 'default'.
=> Fix the Community page search for Rooms

client/src/Components/UI/ContentBox/contentBox.css, client/src/Layout/Dashboard/MainContent/resourceList.css
Preview, Replayer, and Expand icons were getting cut off on smaller screens. 
This PR addresses that by adding a minWidth to ResourceList Container and Column.
=> ContentBox and ResourceList minWidth allows space for each custom icon

client/src/Components/UI/ContentBox/contentBox.css
This prevents facilitator ContentBox from spilling over into participant ContentBox's space.
=> Give ContentBox Container a maxWidth

client/src/Layout/SelectableBoxList/SelectableBoxList.js, server/controllers/RoomController.js
On occasion, a room might have duplicate members (this is a legacy bug that shouldn't be able to happen anymore because of changes to the interface). This PR allows a more graceful way of handling this ill-formed room on the Archive page.
=> Allow archive to handle repeated members

client/src/Components/UI/ContentBox/SelectableContentBox.css
This is done to keep SelectableContentBox within its ResourceList column. 
Prior to this PR, SelectableContentBox spilled out of its column.
=> Giv SelectableContentBox container the same css as ContentBox container

server/routes/auth.js
This is an attempt to fix a bug that prevents Desmos Activities from referencing their teacher.desmos genesis.
=> Load desmosLink into activity tabs during login

client/src/Containers/RoomLobby.js
This PR helps to ensure anonymity in a room with aliased usernames by hiding the Members tab for non-facilitators in that room.
=> Hide the Room Members tab for participants if aliasing is on

client/src/Layout/Dashboard/SidePanel/sidePanel.css
Previously, the side panel button was positioned on top of this border line.
=> Add space between side panel button and the line underneath the button

client/src/Layout/Facilitator/Facilitator.js
This PR helps unify the change from "Activity" to "Template" and is shown to a user when they choose to become a facilitator.
=> When you become a facilitator, create a "Template". It used to be "Activity"

client/src/Components/UI/ContentBox/ContentBox.js, client/src/Components/UI/ContentBox/SelectableContentBox.js, client/src/Layout/BoxList/BoxList.js, client/src/Layout/SelectableBoxList/SelectableBoxList.js, server/controllers/RoomController.js
This PR will allow archived rooms to be searched by their last true update timestamp (i.e., the timestamp of the last event).
=> Don't update the room timestamp when archiving and unarchiving

client/src/utils/groupings.js
This PR address an error specifically regarding reusing a grouping with a deleted room. 
Previously, if you clicked to reuse a grouping with a deleted room the app would crash because the necessary room data could not be found.
Now, groupings with deleted rooms are simply filtered out and not shown in the Assign dropdown menu.
=> Don't display grouping (in reuse or edit assignments) if grouping has one or more deleted rooms

client/src/Components/UI/Modal/TrashModal.js
Previously, for example, if you deleted a room from a course lobby, you'd be redirected to myVMT. Now, you'll go back to the course lobby.
=> On delete: redirect to previous page, if possible, else go to myVMT

client/package.json
It turns out that "3.1.4-1592" is fine but "3.1.4.1592" is not (on staging)
=> correct way of doing pi versioning

client/src/Containers/Create/MakeRooms/AddParticipants.js, client/src/Containers/RoomLobby.js
Address room deletion bug where no room members are found.
Pass due date as null if not provided to address "Not Set" type warning.
Make roster search case insensitive.
=> Roster fixes

client/src/utils/utilityHooks.js
This PR address a 414 error we encountered by passing too many ids through the request header.
Now, we limit the amount of ids passed to 50.
=> Limit the amount of ids passed to server in Monitor & Course Preview

client/src/Components/Form/Checkbox/checkbox.css, client/src/Components/UI/ContentBox/Icons/icons.css, client/src/Components/UI/ContentBox/SelectableContentBox.css, client/src/Components/UI/ContentBox/SelectableContentBox.js, client/src/Containers/Archive.css, client/src/Containers/Archive.js, client/src/Containers/RoomLobby.css, client/src/Layout/Archive/Archive.js, client/src/Layout/Dashboard/MainContent/ResourceList.js, client/src/Layout/Dashboard/MainContent/resourceList.css, client/src/Layout/SelectableBoxList/SelectableBoxList.css
- Display number of resources for user lists (not in Community / Dashboard)
- Display total number of archived rooms on Archive page
- Fix privacy/roomType icon misalignment by giving Icon a set width
- Fix SelectableContentBox extending beyond it's boundary (e.g. extending into "Rooms I'm a Member of")
- Give custom icons (preview, archive, etc.) a set font-weight to account for different browsers. Safari, for example, defaulted the font-weight to be too small which made the icons look too insignificant.
=> Resource list styling

client/src/Components/UI/ContentBox/SelectableContentBox.css
min-width of 32vw made the selectable content box too large on certain screen widths
=> Undo min-width to keep selectable content box contained within its column

client/src/Containers/Create/MakeRooms/MakeRooms.js
Previously, remainders were added to random rooms which was unclear and made it possible for >1 remainder participant to end up in the same room.
=> Add remainders to rooms numerically, starting with room 1

client/src/Containers/Course.js, client/src/Layout/Dashboard/MainContent/ResourceList.js, client/src/Routes/MyVmt.js
Add the ability to archive rooms from the Course lobby.
This pr includes changes to how a course is loaded. Previously, we used withPopulatedCourse to allow facilitators to see all of the course's resources. This hindered a course's ability to live update the rooms list after archiving. Since facilitators now have access to all course resources by default, we can confidently live-load the course from the redux store, which accurately reflects archiving. 
This is a rather big change and will need to be monitored on staging.
=> Archive course rooms

client/src/store/actions/rooms.js
This pr addresses an issue that created a temporary blank room when archiving multiple rooms at once from within a Course or Template rooms list.
=> Remove room from course & activity if needed when archiving multiple rooms at once

client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
Previously, students added from another course could not be removed from rooms, neither when editing an assignment nor when reusing an assignment. Now they can be unselected as needed.
=> One more 🐛 fix

client/src/Containers/Workspace/Workspace.js
Remove the ability to create snapshots as a way to test out their affect on db bandwidth and process CPU usage.
=> Comment out snapshot functionality

client/src/Containers/Replayer/SharedReplayer.js, client/src/Containers/Workspace/ActivityWorkspace.js, client/src/Containers/Workspace/DesmosActivity.js, client/src/Containers/Workspace/Tabs.js, client/src/Containers/Workspace/Workspace.js
This PR simplifies and fixes the underlying code having to do with participants switching among tabs in a math space. Users might notice fewer syncing issues between tabs (or none, hopefully). Additionally, this PR fixes a bug whereby the notification icon (the spinning explanation point) sometimes appeared in the current tab.
=> Refactor of Tabs in a math space

client/src/Containers/Monitoring/MonitoringView.js, client/src/Containers/Monitoring/RoomsMonitor.js, client/src/Containers/Monitoring/monitoringView.css
This PR changes Monitoring such that only rooms that are visible on the user's screen will update. This approach should reduce the server load that sometimes occurs when someone is on the monitoring tab.
This PR also fixes the bug whereby room selections weren't being saved when navigating away and back to the monitoring page.
Note that this PR implements the change only to Monitoring right now. If we find that this approach works, we will also implement it in CoursePreview and Template Preview.
=> New approach to monitor updates

server/controllers/RoomController.js, server/routes/api.js
Change the strategy for populating rooms from the DB to use Mongo directly rather than Mongoose. Theoretically, a Mongo pipeline should be more efficient than using Mongoose find plus multiple populate() calls.
=> Populate via pipeline

client/src/Containers/RoomLobby.js, client/src/Layout/BoxList/BoxList.js
Hide the following features for participants viewing aliased rooms:
- Preview & Stats tabs in the Room Lobby
- Preview icon in myVMT
=> Hide alias features

client/src/Containers/Archive.js, client/src/Containers/RoomLobby.js, client/src/Layout/Archive/Archive.js, client/src/Layout/CourseRooms/CourseRooms.js, client/src/Layout/Dashboard/MainContent/ResourceList.js, client/src/Layout/SelectableBoxList/SelectableBoxList.css, client/src/constants.js, client/src/utils/icons.js, client/src/utils/index.js
Previously, Google icons were created in each file they were used in. 
Now, if we need to change a Google icon only one file needs updated.
=> Centralize Google Icons into utils/icons

client/src/Containers/Workspace/Workspace.js, client/src/utils/utilityHooks.js
In Workspace componentDidMount, API.put('tabs', currentTabId, ...) was failing because we hadn't yet retrieved the currentTabId from the controlState and instead used the old method of retrieving from state, which no longer tracks currentTabId. 
All of this is triggered by a release control update event.
=> Tab update bug fix on release control

server/routes/api.js
This error occurred in a facilitator's course lobby.
=> Fix Error: Cannot set headers after they are sent to the client

client/src/Components/CurrentMembers/CurrentMembers.js, client/src/Containers/Replayer/SharedReplayer.js, client/src/Containers/Workspace/Workspace.js, client/src/store/reducers/activitiesReducer.js
This PR fixes some errors in how control was indicated in the Current Members list, especially when multiple people can be in control (independent tab control):
- anyone in control on any tab will now be highlighted in the Current Members list
- The name of the person currently in control on the current tab will show in the information area above the members' list
PR also includes some code cleaning and documentation.
=> Corrects bugs in how control is indicated in the Current Members list

client/src/Containers/Stats/statsReducer.js
This pr fixes an error in fetching course stats that occured when a course has an unusually large number of highly active rooms.
=> Fix stack overflow error by using for loops instead of math.min & math.max

client/src/Components/CurrentMembers/CurrentMembers.js, client/src/Containers/Workspace/DropdownTabs.js
Remove "Tab:" from the tabs dropdown & add a colon to the tab number in the current members list.
=> Cleanup tab name in DropdownTabs & CurrentMembers

client/src/Containers/Workspace/Workspace.js, client/src/utils/controlMachine.js, server/sockets.js
This PR implements a popup box that appears to the person who is in control (of a room or a particular tab) when someone requests control. The person in control can then either release control or take one more minute. After that minute, control automatically releases.  If the person who requested control cancels that request, the person in control remains in control until they release control or idle for more than a minute.
=>  Popup when control requested

client/src/Containers/Workspace/Workspace.js, client/src/utils/controlMachine.js
This PR fixes a Desmos Activity cloned tab bug that acted as though multiple participants were in control of the same tab even though they were in control of different tabs.
=> Use controlMachine to determine room control per tab

client/src/Containers/Create/NewTabForm.js, client/src/Containers/Workspace/DesmosActivity.js, client/src/Containers/Workspace/DesmosGraph.js
Activity markers:
- ensure that events are added to the log only once
- previously, Desmos Activity & potentiallyDesmos Graph tabs would duplicate events in the log based on the number of tabs of those type in a room. For example, in a room with 3 Desmos Activity tabs, events would be duplicated 3 times causing issues in the Chat
=> Fix chat issue related to Detailed Chat's activity markers & allow for ggb tab creation 

server/sockets.js
This PR recognizes when a user has either closed the browser tab containing VMT or navigates away. When this happens, the server acts as if the user left the room, sending a message to other users in the room ("XXX exited unexpectedly from VMT") and releasing control if that user had been in control.
=> Handle user disconnect from VMT

client/src/Containers/Create/NewResource/Step1.js, client/src/Containers/Create/NewResource/Step2Copy.js
We're disabling this for now for the following reasons:
* useUIState caching the loadedTemplates caused severe lag on some user's computers 
* The search functionality is off by one. For example, searching "4" yielded no results but searching "44" yielded the results for the "4" search.
=> Disable search templates

client/src/Components/UI/RoomSettingsDropdown/RoomSettingsDropdown.js
Filter out unsupported room settings, e.g. controlByTab, that caused the app to crash when reusing groupings that had used that setting.
=> 🐛 Fix issue related to unsupported room settings

client/src/Components/CurrentMembers/CurrentMembers.js, client/src/Containers/Workspace/Workspace.js
If there's only 1 tab, don't display the colon after the usernames.
=> Fix CurrentMembers tabNum display & minor code cleanup

client/src/Components/Navigation/NavItem/NavItem.js, client/src/Layout/AdminDashboard/AdminDashboard.js, client/src/Layout/Community/Community.js
In Community: Show "Load More Results" & keep Community nav link underlined when viewing templates or courses.
In Dashboard: Move "Load More Results" to top of page like in Community & Archive
=> Community & Dashboard Load More Results fixes + keep Community NavItem underlined while in Community

client/src/Containers/RoomLobby.js, client/src/Layout/BoxList/BoxList.js, client/src/Layout/SelectableBoxList/SelectableBoxList.js, client/src/Routes/MyVmt.js, client/src/utils/index.js, client/src/utils/urls.js
According to Routes/MyVMT.js, we need the path to be in the form:
'myVMT/courses/:course_id/activities/:activity_id/rooms/:room_id/:resource'
if the item has a course, we need to add it to the path
if the item has an activity, we need to add it to the path after the course
if the item has a room, we need to add it to the path after the activity
=> Fix how URLs are constructed when clicking on resources, add templates to breadcrumbs

client/src/Routes/MyVmt.js
Fixed an error whereby an unrecognized route was being generated for rooms from standalone  templates.
=> HOTFIX: bad room link

client/package.json, client/src/Components/IdleDetector.js
* Increase timeout to the production value of 30 min
* keep all the logs in case testing is needed on vmt-staging. The logging will be removed before deploying to production.
=> Bump timeout to 30 min

client/src/Components/SortUI/SortUI.js, client/src/Containers/Monitoring/CourseMonitor.js, client/src/Containers/Workspace/Workspace.js, client/src/utils/utilityHooks.js
The rooms in Course Preview will be sorted in reverse chronological order as per the updatedAt field from the DB in the following cases:
- the user leaves and reenters course preview (e.g., entering, making a change, then leaving a room)
- the user selects a different filtering timeframe from the dropdown
- the user refreshes the browser window (as has always been the case)
- the user logs out and back in (as has always been the case)
This PR also adds filtering timeframes of 3, 6, and 9 months.
=> Better updating of course preview

client/src/Components/SortUI/SortUI.js, client/src/Containers/Monitoring/AllRoomsMonitor.js, client/src/Containers/Monitoring/CourseMonitor.js, client/src/Containers/Monitoring/RecentMonitorAlt.js, client/src/Containers/Monitoring/RoomsMonitor.js
This PR implements sortable monitors. There are two alternatives presented for review:
1. In course monitor, the sorting looks similar to the one in MyVMT. It is above the toggles for the room and it allows for sorting by name or last updated, in either direction. It also allows filtering by room name.
2. The MyVMT monitor is simpler, with options to allow sorting by name or last updated, in either direction. The sort options are placed to the left of the warning for admins (if it's there).
These are two alternative designs for monitor sorting. Once decided, either (or another alternative) can be implemented in any or all monitors.
Still to implement: A refresh button rather than the message that's beneath the monitor heading.
=> Sortable monitors

client/src/utils/utilityHooks.js
This PR changes the screen snapshots taken of a mathspace from storage in PNG format to a more efficient, lower quality format (WebP at 10% quality). There seems to be minimal difference visually between the high-quality PNG and low quality WebP thumbnails. Importantly, the low-quality WebP thumbnails are 20-30% of the size of the PNG thumbnails, potentially making database access and data transfer easier on the servers.
=> Change snapshots from png to lossy webp

client/src/Layout/Dashboard/MainContent/ResourceList.js, server/controllers/ActivityController.js, server/controllers/RoomController.js
This PR fixes a bug whereby a Pyret Template not given a URL would not correctly pass along any material to rooms created from it.
This PR also removes the errant "Create" button from the Rooms area of templates.
=> Pyret template corrections

client/src/Containers/Create/NewTabForm.js, client/src/Containers/Workspace/ActivityWorkspace.js, client/src/Containers/Workspace/DesmosActivityEditor.js, client/src/Containers/Workspace/PyretActivity.js, client/src/Containers/Workspace/PyretTemplateEditor.js, client/src/Containers/Workspace/Tools/ActivityTools.js, client/src/Model/TabTypes.js
For Desmos Activity and Pyret rooms, allow the editor of a template to change the source URL/activity code of a tab. Useful if the person made a mistake originally.
=> Editing tab URLs

client/src/Containers/Workspace/Workspace.js, client/src/Layout/Dashboard/MainContent/RoomDetails.js, client/src/store/reducers/roomsReducer.js
Removing the chat from rooms in the redux store should reduce the memory burden of 1000s of rooms.
=> Remove chat from redux store; replace with chat count

client/src/store/reducers/roomsReducer.js, server/app.js, server/controllers/UserController.js, server/models/Room.js, server/routes/auth.js
After some investigation, it seems that the bandwidth spikes on the database server might be due to the logging in of users who have 1000s of rooms. This PR addresses this issue in two ways:
1. Implement compression of data between the database and application servers (enable built-in functionality of Mongoose)
2. Convert the chat field of all rooms into a 'chatCount' field. The chat field is no longer held on the client side unless someone is actually in a room.
=> Handle bandwidth issues with DB

client/src/Components/Importer/dataValidation.js
Adds validation of the general structure of new emails (i.e., not blank and not corresponding to existing users) during import. Note that this implements only a basic email format check (X@X.X, where X one or more characters that are not a space nor an at sign).
=> Validate email structure on import
