mathematicalthinking/vmt

client/src/Components/UI/ContentBox/ContentBox.js
client/src/Components/UI/ContentBox/contentBox.css
client/src/Components/UI/ContentBox/expand.js
client/src/Layout/BoxList/boxList.css

show less content at first, expand for more

Content box re style

---

client/src/Components/Chat/chat.css
client/src/Components/CurrentMembers/currentMembers.css
client/src/Containers/Replayer/GgbReplayer.js
client/src/Containers/Replayer/Replayer.js
client/src/Containers/Workspace/GgbGraph.js

completely change how we're dragging the marker on the progress bar so if we're going backwards in time we 'undo' the construction rather than rebuild it from scratch up to the new point

Replayer remove event for rw

---

app.js
client/src/store/actions/activities.js
client/src/store/actions/courses.js
client/src/store/actions/rooms.js
client/src/store/actions/user.js
config/passport.js
controllers/CourseController.js
controllers/RoomController.js
cypress/support/index.js
middleware/api.js
middleware/errors.js
middleware/utils.js
middleware/utils/helpers.js
middleware/utils/request.js
package-lock.json
package.json
routes/api.js
routes/auth.js
routes/desmos.js

Add middleware for verifying authentication, resource names/ids, content for put/post requests
Return errors from backend in consistent format

Middleware

---

client/src/Components/UI/Button/Button.js
client/src/Containers/MyVMT.js
client/src/Layout/Dashboard/SidePanel/SidePanel.js
client/src/Layout/Dashboard/SidePanel/sidePanel.css
cypress/integration/roles.js

Refactor toggle view to use single icon instead of 2 separate buttons
Update role integration tests

Toggle view

---

client/src/App.js
client/src/Components/Background/Background.js
client/src/Components/Chat/Chat.js
client/src/Components/EditableText/EditableText.js
client/src/Components/UI/Avatar/Avatar.js
client/src/Components/UI/Member/Member.js
client/src/Containers/Activity.js
client/src/Containers/Course.js
client/src/Containers/Create/NewResource/NewResource.js
client/src/Containers/Create/NewResource/Step2New.js
client/src/Containers/MyVMT.js
client/src/Containers/Replayer/GgbReplayer.js
client/src/Containers/Room.js
client/src/Containers/Workspace/Chat.js
client/src/Containers/Workspace/GgbGraph.js
client/src/Containers/Workspace/Workspace.js
client/src/ErrorBoundary.js
client/src/Layout/Dashboard/MainContent/ActivityDetails.js
client/src/Layout/Dashboard/MainContent/RoomDetails.js
client/src/Layout/Dashboard/SidePanel/SidePanel.js
client/src/Layout/Homepage/Homepage.js
client/src/Layout/Homepage/homepage.css
client/src/Layout/Workspace/Workspace.js
client/src/Routes/MyVmt.js
client/src/colors.css
client/src/store/reducers/loadingReducer.js
cypress/integration/editMembers.js

* Fixed Broken Geogebra hamburger menu
* Hide functionality that is unfinished or broken
* Added an Error Boundary around all myVMT stuff and error message to the homepage if redirected there because of an error.
* Got rid of over fetching user's rooms in Containers/Activity
* Fixed replayer breaking on open if no starting point

Hide broken functionality

---

app.js
client/src/Containers/Workspace/GgbGraph.js

fixed a type preventing the build file from being served on all routes.

small fixes

---

app.js
client/src/Containers/Workspace/ActivityWorkspace.js
client/src/Containers/Workspace/GgbActivityGraph.js
client/src/Containers/Workspace/GgbGraph.js

* Fixes bug where activities tabs were not being populated resulting in blank workspaces
* Also fixed typo preventing refresh and loading react app from any route in production

Populate activity

---

client/src/Containers/Course.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/makeRooms.css
client/src/Containers/Create/NewResource/NewResource.js
client/src/Containers/Workspace/ActivityWorkspace.js
client/src/Containers/Workspace/GgbActivityGraph.js
client/src/Containers/Workspace/NewTabForm.js
client/src/Layout/Workspace/Workspace.js
client/src/store/actions/activities.js
client/src/store/actions/index.js
controllers/ActivityController.js
controllers/RoomController.js
controllers/UserController.js
routes/api.js

* Upload a file when creating a new tab in an activity or room #111 
* Allow creator of an activity to manipulate their constructions
* Fixed assign activity randomly

Tab file upload

---

app.js
client/package-lock.json
client/package.json
client/src/Components/EditableText/EditText.js
client/src/Components/Error/ErrorToast.js
client/src/Components/Error/errorToast.css
client/src/Components/HOC/Error.js
client/src/Components/HOC/error.css
client/src/Components/index.js
client/src/Containers/Activity.js
client/src/Containers/Course.js
client/src/Containers/Room.js
client/src/Layout/Confirmation/Confirmation.js
client/src/Layout/Dashboard/MainContent/ActivityDetails.js
client/src/Layout/Dashboard/MainContent/RoomDetails.js
client/src/Routes/MyVmt.js
client/src/store/actions/actionTypes.js
client/src/store/actions/activities.js
client/src/store/actions/courses.js
client/src/store/actions/index.js
client/src/store/actions/loading.js
client/src/store/actions/rooms.js
client/src/store/reducers/loadingReducer.js
controllers/RoomController.js
cypress/integration/z-editResources.js
cypress/plugins/index.js
routes/test.js

* Editing resource info persists closes #101
* All updates are optimistically rendered and then un-updated if the request fails #74
* Accompanying tests

Editing resource

---

client/src/Components/Form/Dropdown/Dropdown.js
client/src/Components/HOC/SocketProvider.js
client/src/Components/Search/Search.js
client/src/Components/Search/search.css
client/src/Components/UI/Member/Member.js
client/src/Components/UI/Member/member.css
client/src/Components/index.js
client/src/Containers/Course.js
client/src/Containers/Members/Members.js
client/src/Containers/Members/SearchResults.js
client/src/Containers/Members/members.css
client/src/Containers/Room.js
client/src/store/actions/access.js
client/src/store/actions/courses.js
client/src/store/actions/index.js
client/src/store/actions/rooms.js
client/src/store/actions/user.js
client/src/store/reducers/coursesReducer.js
client/src/store/reducers/index.js
client/src/store/reducers/roomsReducer.js
client/src/utils/apiRequests.js
controllers/CourseController.js
controllers/RoomController.js
controllers/UserController.js
cypress/fixtures/user6.js
cypress/integration/access.js
middleware/api.js
models/Notification.js
routes/api.js
seeders/users.seeder.js

closes #138 
* Search for users in room/course member tabs
* Immediately add user to room/course after search
* When invited user logs in they'll have an "invitation" notification. When they go to the resource they can decide to join or remove themself from a resource. 
* Changed canModify middleware to allow users to remove themselves (regardless of facilitator status) from a room or course.
* Wrote accompanying tests

User search

---

README.md
client/src/App.js
client/src/Components/CurrentMembers/CurrentMembers.js
client/src/Components/Navigation/HomeNav/HomeNav.js
client/src/Components/Navigation/HomeNav/homeNav.css
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/Step2Course.js
client/src/Containers/MyVMT.js
client/src/Containers/Replayer/GgbReplayer.js
client/src/Containers/Replayer/Replayer.js
client/src/Containers/Workspace/ActivityWorkspace.js
client/src/Containers/Workspace/GgbActivityGraph.js
client/src/Containers/Workspace/GgbGraph.js
client/src/Containers/Workspace/ggbUtils.js
client/src/Layout/About/About.js
client/src/Layout/BoxList/BoxList.js
client/src/Layout/Dashboard/MainContent/RoomDetails.js
client/src/Layout/Homepage/Homepage.js
client/src/configureStore.js
controllers/RoomController.js
models/Event.js
models/Tab.js
sockets.js

Perspective

---

controllers/CourseController.js
controllers/RoomController.js
models/Room.js

Delete stale ntfs

---

client/src/Components/UI/Button/button.css
client/src/Containers/Room.js
client/src/Containers/Workspace/GgbGraph.js
client/src/Containers/Workspace/Tabs.js
client/src/Containers/Workspace/Workspace.js
client/src/Layout/BoxList/boxList.css
client/src/Layout/Dashboard/MainContent/RoomSettings.js
client/src/Layout/Dashboard/MainContent/roomSettings.css
client/src/Layout/Dashboard/index.js
client/src/colors.css
models/Room.js

Room settings

---

client/src/Containers/Community.js
client/src/Layout/BoxList/BoxList.js
client/src/Layout/BoxList/boxList.css
client/src/Layout/Community/Community.js
client/src/Layout/Community/community.css
client/src/utils/apiRequests.js
controllers/ActivityController.js
controllers/CourseController.js
controllers/RoomController.js
routes/api.js

addresses most of #99 
still need to add filtering, search by facilitators, and pagination on myVMT

Pagination

---

client/src/Components/UI/Avatar/avatar.css
client/src/Components/UI/Button/button.css
client/src/Containers/Workspace/GgbGraph.js
client/src/Containers/Workspace/Tabs.js
controllers/CourseController.js
docs/Geogebra.md
docs/Guide.md
models/Event.js
package-lock.json
package.json
routes/api.js
sockets.js

closes #168 
* Add a buffer in sendEvent() by creating a cancellable setTimeout. If events come in fast enough we cancel the previous event emitter and batch the events together.
If the event is an update we figure out how many points the shape we're updating has and attach that to the data object being sent over the socket.
* In socket.on('RECEIVE_EVENT') we call recursiveUpdate() if the event type includes batch. If it is an update event we chop the events array into pieces based on the number of points of a shape and then update all of those points at once. If we updated one point at a time it would look like example 2 in #168. If we updated every event at once it would not look like a drag. 
We're also placing this update in a setTimeout so that the browser paints the update before …

Sending end

---

client/src/Components/Chat/chat.css
client/src/Containers/Activity.js
client/src/Containers/Course.js
client/src/Containers/Room.js
client/src/Containers/Workspace/GgbActivityGraph.js
client/src/Layout/Dashboard/SidePanel/SidePanel.js
client/src/Layout/Dashboard/SidePanel/sidePanel.css
client/src/Layout/Workspace/Workspace.js
client/src/Layout/Workspace/workspace.css
package.json

Workspace layout

---

client/src/Containers/Replayer/GgbReplayer.js
client/src/Containers/Replayer/Replayer.js
client/src/Containers/Workspace/GgbGraph.js
client/src/Layout/Homepage/Homepage.js
models/Event.js
sockets.js

change how we capture dragging of shapes

New drag capture

---

client/src/Components/ToolTip/ToolTip.js
client/src/Components/ToolTip/toolTip.css
client/src/store/reducers/roomsReducer.js

closes #182 
Sets the tool tip to fixed instead of absolute...uses the tool tip container to determine position of fixed tool tip.

Tool tip overflow

---

.travis.yml
app.js
client/.env
client/src/Containers/Workspace/ActivityWorkspace.js
client/src/Containers/Workspace/GgbActivityGraph.js
client/src/Containers/Workspace/GgbGraph.js
client/src/Containers/Workspace/Workspace.js
client/src/Layout/Workspace/Workspace.js
middleware/api.js
package.json

Ggb files uploaded as part of the room/activity creation process were not being loaded on workspace entry.
initializeGgb was being called twice which interrupted/restarted the file read process. 
to fix we added an instance variable on ggbGraph.js and ggbActivityGraph.js to track whether the file had already been loaded

Fix file upload

---

client/src/Components/Navigation/DropdownNavItem.js
client/src/Components/Navigation/NavItem/NavItem.js
client/src/Components/Navigation/Navbar.js
client/src/Components/UI/Modal/PrivateAccess.js
client/src/Components/UI/Modal/PublicAccess.js
client/src/Components/UI/Modal/TrashModal.js
client/src/Containers/Activity.js
client/src/Containers/Create/NewResource/NewResource.js
client/src/Containers/Members/Members.js
client/src/Containers/Profile.js
client/src/Containers/Replayer/SharedReplayer.js
client/src/Containers/Room.js
client/src/Containers/Workspace/GgbGraph.js
client/src/Layout/Profile/Profile.js
client/src/Layout/Profile/profile.css
client/src/store/actions/courses.js
client/src/store/actions/rooms.js
client/src/utils/apiRequests.js
config/passport.js
controllers/CourseController.js
controllers/RoomController.js
cypress/fixtures/user7.js
cypress/integration/admin.js
middleware/api.js
routes/api.js
seeders/users.seeder.js
sockets.js

added tests to previous PR and ability for admin to create other admins

Admin role

---

client/src/Components/CurrentMembers/CurrentMembers.js
client/src/Components/HOC/SocketProvider.js
client/src/Components/HOC/socketProvider.css
client/src/Components/HOC/socketProvider.utils.js
client/src/Components/Navigation/HomeNav/HomeNav.js
client/src/Components/Navigation/NavItem/navItem.css
client/src/Components/Navigation/Navbar.js
client/src/Components/Notification/notification.css
client/src/Containers/Workspace/Workspace.js
client/src/Layout/Dashboard/dashboard.css
client/src/Routes/MyVmt.js
client/src/utils/apiRequests.js
models/Notification.js
models/Room.js

fix styling of ntf on navabr
show ntf on navbar when in a workspace
show toasts for ntf on every page

Workspace refactor

---

.prettierrc.json
client/src/Containers/Replayer/EncompassReplayer.js
client/src/Containers/Replayer/Replayer.js
client/src/Containers/Replayer/SharedReplayer.js
middleware/api.js
package-lock.json
package.json

Add functionality for receiving messages from encompass in SharedReplayer
Share replayer state with encompass

Enc replayer share

---

client/src/Components/InfoBox/InfoBox.css
client/src/Components/InfoBox/InfoBox.js
client/src/Components/Navigation/Navbar.js
client/src/Components/Navigation/navbar.css
client/src/Components/index.js
client/src/Containers/Members/Members.js
client/src/Containers/Workspace/GgbGraph.js
client/src/Containers/Workspace/Workspace.js
client/src/Containers/Workspace/graph.css
client/src/Containers/Workspace/tabs.css
client/src/Layout/BoxList/BoxList.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Layout/Dashboard/MainContent/RoomDetails.js
client/src/Layout/Dashboard/MainContent/roomDetails.css
client/src/Layout/Homepage/Homepage.js
client/src/Layout/Workspace/Workspace.js
client/src/Layout/Workspace/workspace.css
cypress/integration/00_notifications.js
sockets.js

* Fixes room falling out of sync when a new user enters in the middle of shape creation
* Removes socket connection when leaving room
* Minor style updates to workspace and room details page
* Fix multiple tabs not loading

Socket bugs

---

client/src/App.js
client/src/Components/HOC/error.css
client/src/Containers/Replayer/index.js
client/src/Containers/Workspace/ActivityWorkspace.js
client/src/Containers/Workspace/DesmosActivityGraph.js
client/src/Containers/Workspace/DesmosGraph.js
client/src/Containers/Workspace/GgbActivityGraph.js
client/src/Containers/Workspace/Tools/ActivityTools.js
client/src/Containers/Workspace/Workspace.js
client/src/Routes/MyVmt.js
client/src/store/actions/index.js
client/src/store/actions/rooms.js
server/cypress/integration/forgotPassword.js
server/sockets.js

* added an error message for replayers loaded with no events to replay.
* fixed desmosGraph, desmosActivityGraph, and geogebraActivityGraph to work with tab Ids instead of tab indexes
* @todo write tests for entering activities

Errormessage ui

---

client/src/Components/Form/RadioBtn/radioBtn.css
client/src/Components/Navigation/CustomLink/CustomLink.js
client/src/Components/Navigation/HomeNav/HomeNav.js
client/src/Components/Navigation/NavItem/NavItem.js
client/src/Components/Navigation/NavItem/navItem.css
client/src/Components/Navigation/Navbar.js
client/src/Components/Search/Search.js
client/src/Components/Search/search.css
client/src/Components/index.js
client/src/Containers/Community.js
client/src/Layout/Community/Community.js
client/src/Layout/Community/community.css
server/controllers/ActivityController.js
server/controllers/CourseController.js
server/controllers/RoomController.js
server/cypress/integration/community.js

* search community resources by name, description, instructions
* include search term and filter in url so we can navigate back to previous queries
* accompanying tests 
todo: #246 search by user

Search filters

---

server/package.json

Separate scripts for running cypress on ci

---

client/src/Components/Chat/Message.js
client/src/Components/Navigation/DropdownNavItem.js
client/src/Components/Navigation/HomeNav/HomeNav.js
client/src/Components/Navigation/NavItem/NavItem.js
client/src/Components/Navigation/Navbar.js
client/src/Containers/Replayer/SharedReplayer.js
client/src/Containers/Stats/stats.utils.js
client/src/Containers/Workspace/Chat.js
client/src/Containers/Workspace/DesmosGraph.js
client/src/Containers/Workspace/Tools/Awareness.js
client/src/Containers/Workspace/Tools/Tools.js
client/src/Containers/Workspace/Tools/tools.css
client/src/Containers/Workspace/Workspace.js
client/src/Layout/Homepage/Homepage.js
client/src/Routes/Home.js
client/src/Routes/MyVmt.js
server/models/Message.js

Give more detailed descriptions for desmos events 
Display reference description in awareness window and also in downloadable csv
Add Admin Mode toggle in profile hover menu

Desmos descriptions

---

client/src/Components/Chat/Chat.js
client/src/Components/Chat/chat.css
client/src/Components/UI/Modal/PrivateAccess.js
client/src/Components/UI/Modal/PublicAccess.js
client/src/Components/UI/Modal/modal.css
client/src/Containers/Course.js
client/src/Containers/Create/NewResource/NewResource.js
client/src/Containers/Create/NewResource/RoomOpts.js
client/src/Containers/Create/NewResource/Step2New.js
client/src/Containers/Create/tinyGraphs.utils.js
client/src/Containers/Room.js
client/src/Containers/Workspace/ActivityWorkspace.js
client/src/Containers/Workspace/ControlWarningModal.js
client/src/Containers/Workspace/DesmosGraph.js
client/src/Containers/Workspace/GgbGraph.js
client/src/Containers/Workspace/Tools/ActivityTools.js
client/src/Containers/Workspace/Tools/Tools.js
client/src/Containers/Workspace/Workspace.js
client/src/Layout/Dashboard/MainContent/ActivityDetails.js
client/src/Layout/Homepage/Homepage.js
docs/Workspace.md
server/controllers/ActivityController.js
server/controllers/RoomController.js
server/cypress/integration/admin.js
server/cypress/integration/create.js
server/cypress/integration/workspace.js

Users can copy their own activities in addition to other people's
Users can create a room or activity from an existing room 
- can select a subset of tabs if there is more than 1 tab
Fixes/improvements for admin mode

Copying activities/rooms

---

server/config/app-urls.js

Add staging CORS url
This url should fix **staging** encompass import from vmt.

[Bug] Add staging CORS url

---

client/package-lock.json
client/src/Components/Navigation/HomeNav/homeNav.css
client/src/Containers/Create/NewResource/NewResource.js
client/src/Containers/Create/NewResource/RoomOpts.js
client/src/Containers/Create/NewResource/Step2New.js
client/src/Containers/Create/NewResource/roomOpts.css
client/src/Containers/Replayer/DesActivityReplayer.css
client/src/Containers/Replayer/DesActivityReplayer.js
client/src/Containers/Replayer/SharedReplayer.js
client/src/Containers/Replayer/index.js
client/src/Containers/Workspace/Chat.js
client/src/Containers/Workspace/DesmosActivity.js
client/src/Containers/Workspace/TempWorkspace.js
client/src/Containers/Workspace/Workspace.js
client/src/Layout/Homepage/Homepage.js
client/src/utils/sockets.js
server/package-lock.json
server/package.json
server/sockets.js

Added Desmos Activities and draft replayer.
Added logging to Sockets.
Socket client will only use websockets (disabled long polling)
Updated time stamps for prod

Updated Desmos Activity and Socket Logging

---

server/controllers/RoomController.js

Implements a less data-heavy way to pull admin dashboard information. @TODO: Does not include the names of the active users, just their ids.

:tada: event count from rooms

---

client/src/Components/Chat/Chat.js
client/src/Components/Chat/QuickChatList.js
client/src/Components/Chat/chat.css
client/src/Containers/Workspace/Chat.js
client/src/Containers/Workspace/Tools/Awareness.js
client/src/Containers/Workspace/Tools/Tools.js
client/src/Containers/Workspace/Tools/tools.css
client/src/utils/colorMap.js
server/constants/colorMap.js
server/package-lock.json

Updated chat features, including STT, quick-chats, and updated colorMap

Chat updates

---

client/src/Containers/Course.js
client/src/Containers/Members/ImportModal.js
client/src/Routes/MyVmt.js
client/src/utils/withPopulatedCourse.js
server/controllers/CourseController.js
server/controllers/UserController.js

These changes are a first step to allow course facilitators to work with all resources in a course. With these changes, a newly assigned facilitator can see all course rooms and templates in the facilitator's view of the course. (Previously, facilitators could see only templates and rooms that they owned or were a member of.)
This files should not be merged into the development branch until the implementation of this feature is complete -- i.e., the new facilitator can access and edit all resources.

Course facilitator

---

client/src/Containers/Members/ImportModal.js

During import, allow the user to delete a row.

:tada: row deletion facility

---

client/src/Containers/Members/Members.js
client/src/utils/validators.js

Workflow for importing existing users to a course. 
NOTE: Currently courses allow facilitators to add a user more than once to a course (see line 91 of Members.js)

Import existing user

---

client/src/Containers/Course.js
client/src/Containers/Monitoring/MonitoringView.js
client/src/Containers/Monitoring/ResourceTables.js
client/src/Containers/Monitoring/RoomPreview.js
client/src/Containers/Monitoring/TemplatePreview.js
client/src/Containers/Monitoring/resourceTables.css
client/src/Containers/Workspace/Workspace.js

* Monitor selection table now divided between "Rooms I Manage" and "Rooms I'm a Member of"
* "Course Monitor" renamed to "Preview"
* Cleaned up UI for template preview
* Room preview now allows choice of detailed vs simple chat
* Possible fix for situations in which a non-desmos activity gets "screen based" thumbnails assigned.

UI changes related to Monitoring

---

client/src/Containers/Course.js
client/src/Containers/Members/ImportModal.js
client/src/Routes/MyVmt.js
client/src/utils/withPopulatedCourse.js
server/controllers/CourseController.js
server/controllers/UserController.js

* :tada: facilitators can view any templates or rooms

Course facilitator (#339)

---

client/src/Containers/Members/Members.js
client/src/Containers/Monitoring/MonitoringView.js
client/src/Containers/Monitoring/SelectionTable.js

* Importing
- Updates to prevent usernames from being empty
- Simpler handling of existing users (still a bit off -- not updating sponsor or metadata, but existing user *does* get added)
- Revalidation of data after a row deletion
* Monitoring: Fixed incorrect auto-selection of 5 most recently updated rooms
* Comments added to SelectionTable

better handling of usernames, existing users, room sorting

---

client/src/Components/Chat/chat.css
client/src/Components/ClassList/ClassList.js
client/src/Components/ClassList/classlist.css
client/src/Components/index.js
client/src/Containers/Members/ImportModal.js
client/src/Containers/Members/Members.js
client/src/Layout/ClassCode/ClassCode.js
client/src/Layout/ClassCode/classcode.css
client/src/Layout/Homepage/Homepage.js
client/src/Layout/Homepage/homepage.css

Draft feature to notify course code users of the current account status

Proxy login feat

---

client/src/Containers/Members/ImportModal.js
client/src/Containers/Members/Members.js

⃠ submit validation flow change feature, plus import user username-email mismatch

Import features

---

client/src/Containers/Course.js
client/src/Containers/Members/Members.js
client/src/Containers/Monitoring/RoomPreview.js
client/src/utils/withPopulatedCourse.js
server/controllers/CourseController.js

* secondary facilitators can see all resources in a course
* bug: room icons corrected
* bug: new resources appear for the user (and other facilitators) immediately, without refresh
* in import, we now validate that a Google login user has an email indicated
* small UI change to room preview

Bug fixes and new import validation

---

client/src/Components/UI/ContentBox/ContentBox.js
client/src/Layout/BoxList/BoxList.js
client/src/Layout/Homepage/Homepage.js
server/controllers/RoomController.js

Draft feature to community list

Last updated

---

client/src/Components/CurrentMembers/currentMembers.css
client/src/Containers/Monitoring/MonitoringView.js
client/src/Containers/Monitoring/RoomPreview.js
client/src/Containers/Monitoring/TemplatePreview.js

* Room and Template Preview now have 'attendance' tiles
* Room preview tiles order changed to attendance, chat, thumbnail
* Updated CurrentMember list styling -- font size for current members changed from 16px to 18px.
* In MonitoringView, attendees are sorted whereby people currently in the room are moved to the top of the list

Attendance added to previews

---

client/src/Components/Chat/Chat.js
client/src/Components/UI/ToggleGroup/toggleGroup.css
client/src/Containers/Workspace/Workspace.js
server/app.js
server/package.json

* Options for refresh if a sync problem on client side; updates to how client detects there might be a problem
* UI changes to toggle group
* fix to dev:pc script (and undoing changes to app.js from previous commit)

Sync refresh & pings; toggle group UI; fix to dev:pc

---

client/package.json

update axios package

---

client/package.json

lodash update

---

server/middleware/mt-auth.js
server/models/Notification.js

Possible fix for notifications, which had broken when we upgrade socket.io.  Note that fix involves async/await code, but commented below in the file is a longer .then() based approach (i.e., in keeping with the original coding style) for comparison.

:bug: possible fix for notifications (from socket.io upgrade)

---

client/src/Containers/Activity.js
client/src/Containers/Course.js

Reduce the warnings due to proptype errors

Fixed legacy prop type errors

---

server/package.json

update script for starting encompass from vmt

update npm script dev-enc

---

server/cypress/integration/community.js

Fixed an error *in the testing suite* whereby an automated test failed even though doing the test manually succeeded. Now automated test succeeds.

fixed community test

---

client/src/Components/Form/TextInput/TextInput.js
client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/Step2Course.js
client/src/Containers/Profile.js

draft new feature to randomize course assignments from templates

Random assign feat

---

client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/Step2Course.js

Two changes:
- fixed a bug whereby the assignment matrix 'random' feature didn't work for stand-alone templates
- made Random option (with participants per room) the default.
(NOTE: 🎉 First pair programming by John and Irv)

Assignment matrix

---

client/src/Components/Form/TextInput/TextInput.js
client/src/Components/UI/Modal/BigModal.js
client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/makeRooms.css

This pr improves the ui for the assignment matrix by:
* allowing horizontal scroll on the assignment matrix table
* room names are now multi-lined
* participants column is visible when scrolling horizontally

Compressed assignment matrix

---

client/src/Components/Form/TextInput/TextInput.js
client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/makeRooms.css
client/src/Containers/Create/create.css
client/src/Layout/Homepage/Homepage.js

This pr address changes to the AssignmentMatrix UI in the following ways:
* Horizontal/Vertical scrolling of the table
* Sticky Header/Footer/Left column
* Full room names are always visible

Assignment matrix UI updates

---

client/src/Components/UI/Modal/bigModal.css
client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/Step2Course.js
client/src/Containers/Create/MakeRooms/makeRooms.css
server/package-lock.json

Changes include:
* table is larger, with about 10-15 students visible at a time (depending on screen size)
* facilitators of a course are placed at the bottom of the list and are shown in blue to make them visually distinct
* Other restructuring to simplify the MakeRooms, AssignmentMatrix subsystem.

Updates to AssignmentMatrix UI

---

client/config/paths.js
deploy.sh

* During the build/deploy script, create a zip file that is more convenient for deployment
* Fixed a typo that prevented Encompass from building correctly.

Changes to fix builds

---

.github/dependabot.yml
client/package-lock.json
server/package.json

Package-related issues:
* corrected version of client/package-lock.json
* trying additional config for dependabot.yml
* fix to testserver:pc npm script

Fix package-lock

---

client/src/Layout/Dashboard/MainContent/DashboardContent.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/utils/utilityHooks.js

This PR implements sorting of Rooms, Courses, & Templates on the myVmt screen and within Courses.

ResourceList sort 

---

client/src/Components/Chat/Chat.js

This PR address a render issue wherein the Chat DropdownMenu would disappear after a short amount of time.

Moved Chat DropdownMenu outside of Chat render

---

client/src/utils/utilityHooks.js

Fixed issues with resource sorting:
- disabled search functionality of sort pull down
- made sorting of text not sensitive to case

Updated sort

---

.gitignore
client/.env.example
client/public/index.html
client/src/Components/UI/ContentBox/ContentBox.js
client/src/Containers/Create/NewResource/Step2New.js
client/src/Containers/Replayer/EncompassReplayer.js
client/src/Containers/Workspace/PyretActivity.js
client/src/Containers/Workspace/TempWorkspace.js
client/src/Containers/Workspace/ggbUtils.js
client/src/Layout/Community/Community.js
client/src/Layout/Homepage/Homepage.js
client/src/Routes/Home.js
client/src/utils/apiRequests.js
client/src/utils/appUrls.js
client/src/utils/sockets.js
server/.env.example
server/app.js
server/config/app-urls.js
server/middleware/mt-auth.js
server/middleware/utils/request.js
server/routes/auth.js
server/services/sso.js

This PR does two things:
1. .env files are now specific to a server, rather than having multiple variables that refer to different environments. This means that each server type (prod, staging, test, local) has its own server/.env file.
2. Most client environment files are now defined within the server .env. Prefix an environment file with "REACT_APP_" to have it accessible to the client.
Both of these changes were necessary to allow for Dockerization.

Environment variables changed for Dockerization

---

client/src/Containers/Activity.js
client/src/Containers/RoomLobby.js
client/src/Containers/Workspace/Tools/CreationModal.js

This PR shows the correct template type when new templates are created from existing rooms. In addition:
- the room / template type in the lobby shows all the types represented by the room / template tabs
- In the lobby, the type heading is singular or plural depending on the number of tab types.

Activity Type

---

client/src/Components/UI/ContentBox/ContentBox.js
client/src/Containers/Room.js
client/src/Containers/Workspace/Workspace.js
client/src/Layout/Community/Community.js
server/sockets.js

This PR merges changes from the recent hotfix deployment to prod on 4/29 as well as fixes to bugs discovered as part of the deployment:
- removed one possible source of CPU spikes
- fixed bug that caused huge numbers of "control was removed by the system" to occur
- additional checks that a value for REACT_APP_PYRET_MODE exists (Community and ContentBox)

Recent hotfix deployment

---

README.md
client/package.json
client/public/index.html
client/src/ErrorBoundary.js
client/src/Layout/Dashboard/SidePanel/sidePanel.css
server/app.js

Bug fixes needed for Docker and removal of unneeded package.

Small changes

---

client/src/Components/HOC/OauthReturn.js

Ensure users see correct errors on screen for Google Oauth issues.

Forward login errors returned from mt-sso

---

client/package-lock.json
client/package.json
client/src/Components/HOC/PrivateRoute.js
client/src/Components/Importer/Importer.js
client/src/Containers/Activity.js
client/src/Containers/Course.js
client/src/Containers/Monitoring/CourseMonitor.js
client/src/Containers/MyVMT.js
client/src/Containers/Room.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Routes/MyVmt.js

* Fixed a bug so that now when you add a room member, that person appears in the list immediately
* Course Preview rooms are now shown in reverse chronological order (i.e., most recently updated rooms are first)
* Other internal changes to improve stability of VMT

UI fixes and updates

---

client/src/Containers/Monitoring/CourseMonitor.js
client/src/Containers/Monitoring/TemplatePreview.js

As requested, order is not live, but as of when the course or template was loaded

Previews show rooms in reverse chrono order

---

client/src/Containers/Data/withPopulatedRoom.js

Remove adjectives from alias usernames

---

client/src/Containers/Workspace/ggbUtils.js
server/.env.example
server/app.js

Makes more stable our access to the GeoGebra CDN

Move GGB url from client to server

---

client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/utils/utilityHooks.js

* Provide a default "Last 2 Weeks" option to resource filtering
* Allowing filtering by "More than" timeframes (e.g., show only rooms that are more than a month old)

Resource filtering

---

client/src/Containers/Monitoring/RoomViewer.js
client/src/Containers/Monitoring/Thumbnails.js
client/src/Containers/Monitoring/monitoringView.css
client/src/Containers/Monitoring/roomViewer.css

* Thumbnail in room preview now shows the day and time of when the thumbnail was taken. This timestamp is shown even if there is a pulldown menu for selecting among tabs.
* "Attendance" field in the room preview is now labeled
* Other small UI changes to make the room preview (and room popout) look nicer

UI changes to room viewer

---

client/.eslintrc
client/src/Components/HOC/SocketProvider.js
client/src/Containers/Monitoring/MonitoringView.js
client/src/Containers/Workspace/Tools/DesActivityHelpers.js
client/src/store/actions/rooms.js
server/controllers/RoomController.js

Fixes an issue whereby randomization in Desmos Activities would lead to different results for different room participants. This PR adds initialization when we create a Desmos Activity so that it is placed in the appropriate state before anyone enters the room for the first time.

Desmos Activity Initialization

---

client/src/Containers/Course.js
client/src/Containers/Stats/CourseStats.js
client/src/Containers/Stats/stats.utils.js
client/src/Containers/Stats/statsReducer.js
server/controllers/RoomController.js
server/middleware/utils/helpers.js

This pr gives researchers (and other users) the option to download the exports from all room in a course into a single csv.
The csv contains studentIds, if specified during import, roomNames, and userIds in addition to the usual data in a room export.

Course stats

---

client/src/Containers/Create/NewResource/NewResource.js
client/src/Containers/Create/NewResource/Step2New.js

This pr changes the default room type, during room creation, to Desmos Activity or the last type of room that the user created during the current login session.

Change default room type on room creation

---

client/src/Containers/Activity.js
client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/makeRooms.css

Turn off incompletely implemented groupings functionality so that remaining features can be pushed to production.

Get rid of groupings in preparation for prod deploy

---

client/src/Containers/Stats/CourseStats.js

This pr adds a message on the Course Stats page when loading data & when data is finished loading.

Course Stats loading message

---

client/src/Routes/MyVmt.js

This allows users to refresh without being redirected due to the store not being immediately available.

Set actuallLoggedIn based on node_env

---

client/src/Routes/MyVmt.js

Reverts mathematicalthinking/vmt#578

Revert "Set actuallLoggedIn based on node_env"

---

client/src/Components/Importer/Importer.js
client/src/Containers/Members/Members.js

Add functionality to the import process to delete current non-facilitators and replace the member with newly imported members.

Import to replace

---

client/src/Containers/Workspace/DesmosActivity.js
client/src/Containers/Workspace/DesmosGraph.js
client/src/Containers/Workspace/GgbGraph.js
client/src/Containers/Workspace/PyretActivity.js
client/src/Containers/Workspace/Workspace.js
server/sockets.js

First try at automatic detection of mathspace state being out of sync

Extract SEND_EVENTs from mathspaces into Workspace & detect unsynced state

---

README.md
client/src/Containers/Stats/CourseStats.js
client/src/Containers/Stats/statsReducer.js

Course stats now load with more stability; should no longer get stuck.

Simplify course stats

---

client/src/Containers/Data/withPopulatedRoom.js
server/controllers/ActivityController.js
server/controllers/UserController.js
server/routes/auth.js

* Don't load in tab info on activities
* Show error message if there's a problem loading a room.

limit data loaded on login; better room load error msg

---

server/controllers/RoomController.js

Dashboard now shows all the tab types (Demos Graph, GeoGebra, Desmos Activity, etc.) for rooms in the search result

Put tabtypes into dashboard

---

client/src/Components/UI/ContentBox/ContentBox.js
client/src/Components/UI/ContentBox/DashboardContentBox.js
client/src/Components/UI/ContentBox/expand.js
client/src/Containers/Workspace/RoomInfo.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Layout/Dashboard/MainContent/resourceList.css
client/src/utils/utilityHooks.js

* Filter (when you see a list of resources) now only filters by the last updated date. This allows users to filter by a timeframe but sort on a different property (e.g., name, due date, etc.).
* The default filter is "updated in the last week".
* When you search for resources by their name, the filter switches to "all" to allow users to see the results of the search
This PR includes some other internal updates to simply and stabilize the codebase.

Updates to resource filtering

---

client/src/Containers/Activity.js
client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/EditRooms.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/makeRooms.css
client/src/Containers/Create/MakeRooms/selectAssignment.css
client/src/store/actions/rooms.js
server/models/Activity.js
server/models/Course.js

* "Shuffle" now more evenly distributes participants, not allowing any rooms with leftovers.
* There is now a visual indicator of whether someone has been assigned in an assignment matrix
* When you click "assign," you are warned if someone is not assigned
* Pulldown placeholder messages are now clearer
* When you edit an assignment within a course, the assignment matrix now shows all course members whether or not they were assigned to a room.
* Various bugs associated with assignments have been fixed

Assignment matrix fixes

---

client/src/Components/UI/Member/Member.js
client/src/Containers/Course.js
client/src/Containers/Members/Members.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/store/actions/rooms.js
client/src/store/reducers/roomsReducer.js
client/src/utils/apiRequests.js
server/controllers/RoomController.js

When a course member's role changes from a participant to a facilitator, add that member to each room within the course as a facilitator.
When a course member's role changes from facilitator to participant, change that member's role to participant in each room they were already a member of.

Facilitator access

---

client/src/Containers/Activity.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Routes/MyVmt.js
server/controllers/RoomController.js
server/models/User.js

* Corrected default value for archive information from User collection
* Adjusted method for creating new ObjectIds in RoomController
* Updated how activity is populated to eliminate need for separate reference to all rooms
*

Fixed small errors in archiving

---

client/src/Containers/Activity.js

Temporary for prod deployment. Can still create assignments but editing is still buggy.

turn off assignment edits

---

client/src/Containers/Archive.js
client/src/store/reducers/userReducer.js

These 2 changes handle edge-case errors that occasionally occur in which users are not given an archive object in the Redux store and db.

Create default archive.rooms if it doesn't exist, ignore archive api call if no archive[resource]

---

client/src/Containers/Activity.js
client/src/Containers/Create/MakeRooms/AddParticipants.js
client/src/Containers/Create/MakeRooms/AssignRooms.js
client/src/Containers/Create/MakeRooms/EditRooms.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/SelectAssignments.js
client/src/Containers/Create/MakeRooms/makeRooms.css
client/src/Containers/Monitoring/MonitoringView.js
client/src/Containers/Monitoring/TemplatePreview.js
client/src/Layout/Dashboard/MainContent/DashboardContent.js
client/src/store/actions/rooms.js
client/src/utils/groupings.js
server/routes/api.js

* Correctly use dispatch within edit groupings.
* Groupings names have the following updates:
* Groupings names default to the name of the template from which they're created
* The date and time groupings were created are displayed in the selection dropdown menu
* When the prefix for a grouping is changed, the grouping name changes to the prefix, whereas before it did not.

🎉  Edit Groupings works and Groupings names make more sense now

---

client/src/Containers/Activity.js

Reverts mathematicalthinking/vmt#630

Revert "turn off assignment edits"

---

client/src/Containers/RoomLobby.js
client/src/Layout/Dashboard/SidePanel/SidePanel.js

Put buttons at top of side panel, get rid of room image, use same archive button as elsewhere

Re-style room lobby side panel, archive button

---

client/src/Components/Importer/Importer.js
client/src/Components/Importer/dataValidation.js

Blank usernames are now replaced with a unique username based on the imported user's first and last name.  The username is generated as follows:
- if there's a first and last name, use first name, last initial(s), and a random 2 digit number
- if there's only a first name, use first name and a random 4 digit number
- if there's only a last name, use last name and a random 4 digit number
- if neither first nor last name, user x and a random 6 digit number
In addition, the sponsor/teacher's username is now case insensitive (it's always converted to lowercase).

Bug fixes for and enhancements to import validation

---

client/src/Components/ToolTip/toolTip.css
client/src/Components/UI/ContentBox/SelectableContentBox.css
client/src/Components/UI/ContentBox/contentBox.css
client/src/Components/UI/Modal/BigModal.js
client/src/Components/UI/Modal/bigModal.css
client/src/Containers/Archive.js
client/src/Containers/Course.js
client/src/Layout/Archive/Archive.js
client/src/Layout/BoxList/boxList.css
client/src/Layout/Dashboard/MainContent/resourceList.css
client/src/Layout/SelectableBoxList/SelectableBoxList.css

This PR addresses horizontal scrolling that can occur with resources lists.
The lists look better on smaller screens, but for screens much smaller than a 14" mpb, resource lists can collide into each other.
As well, this PR shows number of participants in course lobby

Working towards more responsive resource lists

---

client/src/Containers/Archive.js
client/src/Layout/Archive/Archive.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Layout/Dashboard/SidePanel/SidePanel.js

also, simplify how Archive manages modals and state

Change message in archive & unarchive modals, move side panel buttons under title

---

client/src/Containers/Archive.js
client/src/Layout/Archive/Archive.js
client/src/Layout/Dashboard/MainContent/DashboardContent.js

After more archived content is loaded, automatically scroll to the bottom of the page.
Use useSelector instead of useStore

Archive scroll to bottom

---

server/controllers/RoomController.js
server/models/Room.js

Reverts mathematicalthinking/vmt#666

Revert "remove ROLE constant as a test"

---

client/src/Components/Navigation/HomeNav/HomeNav.js
client/src/Components/Navigation/Navbar.js
client/src/Containers/Archive.js
client/src/Containers/MyVMT.js
client/src/Containers/RoomLobby.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Routes/Home.js

Remove archiving functionality, keep archiving within the code base. 
This PR assumes that the underlying data structures, routes, and models of archiving will be used in the near future.

Superficially turn off archiving

---

client/src/Containers/Members/Members.js
client/src/Layout/Dashboard/MainContent/ResourceList.js

Restrict access to templates in a Course lobby or within MyVMT to template creators. 
This PR disallows template users to access templates due to an error with groupings and template user access.

Creator template restriction

---

client/src/Containers/Workspace/ControlWarningModal.js

Change text of control warning modal to be clearer when the user has already quested control.

Control warning text

---

client/src/Containers/Create/MakeRooms/MakeRooms.js

Sort the participants by room (as best as possible) when re-using an assignment (the Assign tab of Template).

Sort participants in assignments

---

client/src/Containers/Create/MakeRooms/AssignRooms.js
client/src/Containers/Create/MakeRooms/EditRooms.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Members/Members.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/store/actions/activities.js
server/controllers/ActivityController.js
server/middleware/api.js
server/routes/api.js

This PR allows activity users (course facilitators) to edit & reuse groupings by giving access in api > middleware > canModifyResource.

Give activity users access to modify the activity

---

client/src/Containers/Create/MakeRooms/MakeRooms.js

Reverts mathematicalthinking/vmt#686

Revert "Sort participants in assignments"

---

client/src/Components/Navigation/HomeNav/HomeNav.js
client/src/Components/Navigation/Navbar.js
client/src/Containers/Archive.js
client/src/Containers/MyVMT.js
client/src/Containers/RoomLobby.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Routes/Home.js

Reverts mathematicalthinking/vmt#681

Revert "Superficially turn off archiving"

---

client/src/Containers/Create/MakeRooms/MakeRooms.js

When making a new assignment based on an existing assignment, sort participants by their room (as best as possible).

Sort participants in old and new assignments

---

client/src/Layout/Confirmation/Confirmation.js

It used to be: Go to your dashboard

Change access confirmation msg to: Go to MyVMT

---

client/src/Components/UI/Modal/BigModal.js
client/src/Containers/Activity.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/SelectAssignments.js
client/src/Containers/Monitoring/CourseMonitor.js
client/src/Containers/index.js
client/src/Layout/Confirmation/Confirmation.js
client/src/Layout/Dashboard/MainContent/ActivityDetails.js
client/src/Layout/Dashboard/index.js
client/src/Layout/index.js
client/src/utils/groupings.js
client/src/utils/index.js

Reverts mathematicalthinking/vmt#701

Revert "Various changes"

---

client/package.json
client/src/utils/groupings.js
server/routes/auth.js

This PR fixes a lot of the issues with templates. 
Also, this fixes an error with groupings.

Load full activity on login

---

client/package.json
client/src/Containers/Create/MakeRooms/EditRooms.js

Fix a bug in which EditRooms did not properly access the room id.

Refer to the room id in EditRooms

---

client/src/Components/Chat/Message.js
client/src/Components/GeneralModal.js
client/src/Containers/Workspace/ControlWarningModal.js

This PR implements a new approach to the modal buttons that the user sees if they had requested control and then click in the math space.

Adjust control warning messaging

---

client/src/Components/UI/Modal/bigModal.css
client/src/Components/UI/Modal/modal.css
client/src/Containers/Archive.js

This PR ensures that dialog boxes (modals) always appear on the screen, regardless of whether the screen has been scrolled.

Adjust Modal & BigModal so they are always visible

---

client/src/Containers/Monitoring/RoomsMonitor.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Layout/Dashboard/MainContent/resourceList.css
client/src/utils/utilityHooks.js

This PR places the search box on a resource list (e.g., in MyVMT, in the Rooms tab of a course) underneath the Sort/Updated pulldown menus. This is a more logical place for the search and less visually confusing than putting the search next to the "create" button.

Resource search with sort

---

client/src/Containers/Activity.js
client/src/Routes/MyVmt.js
client/src/utils/index.js
client/src/utils/withPopulatedActivity.js

This PR fixes an error related to users not being able access templates they are facilitators of but not the creator of.

Load Templates from the database if they're not available in the user's Redux store

---

client/src/Containers/RoomLobby.js

This PR addresses an error in loading rooms accessed via the Community.

Fix error when accessing rooms from Community

---

client/src/Containers/Activity.js
server/controllers/RoomController.js

This PR allows the user of Dashboard or Archive to search rooms by the username of a facilitator.

Search by facilitator

---

client/src/Containers/Activity.js
client/src/store/reducers/index.js
client/src/utils/withPopulatedActivity.js
server/controllers/ActivityController.js
server/middleware/api.js

This PR address an issue with template users accessing templates, as well as accessing public templates

Populate templates from the database rather than the Redux store

---

server/controllers/RoomController.js

Reverts mathematicalthinking/vmt#740

Revert "testing about thumbnails"

---

server/controllers/ActivityController.js
server/controllers/CourseController.js

These changes occur in the getPopulatedById method within ActivityController & CourseController.

Mongodb handles arrays vs iterating arrays and passing mongodb each element

---

docs/ResourceCreation.md

Create a template for documenting Resource Creation from a developers perspective.

Begin Resource Creation Doc

---

client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/utils/amIAFacilitator.js
client/src/utils/index.js

For activities, any person with access is considered a facilitator

Centralized check if current user is a facilitator

---

client/package.json
client/src/Containers/Activity.js
client/src/Containers/Create/NewResource/NewResource.js
client/src/store/actions/activities.js
server/controllers/ActivityController.js

This applies to course facilitators and for templates created within a course. 
Currently, standalone templates do not have users.

Add template users to each users' list of activities in the db & to template.users in the Redux store

---

client/package.json
client/src/Components/InfoBox/InfoBox.css
client/src/Components/InfoBox/InfoBox.js
client/src/Components/Search/GenericSearchResults.js
client/src/Components/Search/genericSearchResults.css
client/src/Containers/Create/MakeRooms/AddParticipants.js

Participants for Courses that you are a facilitator of but not the creator of are available to be imported into a new assignment / grouping via the Add Participants modal available in the assignment matrix.

Share rosters initial draft

---

client/package-lock.json
client/package.json

Reverts mathematicalthinking/vmt#760

Revert "trying update to fs-extra"

---

client/src/Containers/Create/MakeRooms/AssignmentMatrix.js

Update ToolTip message for adding participants within the assignment matrix.

Update ToolTip message

---

client/package.json
client/src/Components/Form/Checkbox/Checkbox.js
client/src/Containers/Create/MakeRooms/AddParticipants.js
client/src/Containers/Create/MakeRooms/makeRooms.css

Center and align "Add New Members to Course" checkbox in Add Participants modal

Add to participants alignment

---

client/src/Components/UI/Button/button.css
server/models/Notification.js

This pr fixes a bug that caused a crash for new room invitees.

Convey tabType during Ntf; fix member delete btn css

---

client/src/Containers/Activity.js
client/src/store/actions/rooms.js
server/controllers/RoomController.js

This pr also address the following, previously omitted, unarchive functionality:
- If the room belonged to a course / template add it back to the course / template on unarchive

Archive template rooms

---

client/src/Containers/Create/MakeRooms/AddParticipants.js
client/src/Containers/Create/MakeRooms/makeRooms.css

Layout AddParticipants so that the two InfoBoxes are next to each other and above the buttons, and so that the two InfoBoxes are the same height.

AddParticipants styling

---

client/src/Components/ToolTip/toolTip.css
client/src/Components/UI/ContentBox/ContentBox.js
client/src/Components/UI/ContentBox/Icons/Icons.js
client/src/Components/UI/ContentBox/SelectableContentBox.css
client/src/Components/UI/ContentBox/SelectableContentBox.js
client/src/Components/UI/ContentBox/contentBox.css
client/src/Containers/RoomLobby.js
client/src/Layout/Archive/archive.css
client/src/Layout/BoxList/boxList.css
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Layout/Dashboard/MainContent/resourceList.css
client/src/Layout/Dashboard/SidePanel/sidePanel.css
client/src/Layout/Dashboard/dashboard.css
client/src/Layout/SelectableBoxList/SelectableBoxList.css

Give icons ToolTip, give BoxList icons, change ToolTip text, remove privacy icon on myVMT, group notification bell with customIcons
ResourceList & ContentBoxes alignment / styling, shrink SidePanel, archive list not cut-off on small screens

ResourceList alignment styling, Participant Icons, Shrink SidePanel

---

client/src/Layout/Dashboard/MainContent/ResourceList.js

More accurately represent filter searches throughout myVMT rooms, courses, and templates.

Fix to filter in resource list

---

client/src/store/actions/rooms.js

This pr fixes a bug that would display a blank room after archiving

Fix archive bug

---

client/src/Containers/Create/MakeRooms/AssignmentMatrix.js

Assignment Matrix sorting works and can be sorted by rooms, courses, or alphabetically.

Matrix sorting works :tada:

---

client/src/Containers/Create/MakeRooms/AddParticipants.js

This PR addresses a strobe-y text input issue when searching within AddParticipants

Debounce AddParticipants search

---

client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/makeRooms.css

Remove unnecessary Sort option, give AssignmentMatrix a max-height to allow the entire matrix to fit on screen, and make AssignmentMatrix's bottom border the same styling as other borders on the screen

AssignmentMatrix height, bottom border, and sort dropdown options

---

client/src/Containers/Create/MakeRooms/AddParticipants.js
client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/store/actions/courses.js
client/src/utils/apiRequests.js

This PR fixes the following bugs:
* Switching between types of sorting in assignment matrix sometimes didn't work (now it always works)
* Participants from different courses sometimes weren't assign different colors when editing or reusing an assignment (now they always have the correct colors)
* When searching for users to add to an assignment, typing into the search box was sometimes laggy and buggy (now it isn't)

Various 🐛 fixes

---

client/src/Containers/Archive.js

If no archive or archived rooms found, give totalNumberOfArchivedRooms a value of 0

Better handling of totalNumberOfArchivedRooms

---

client/src/Components/Importer/CourseCodeMemberImport.js
client/src/Components/Importer/CourseCodeMemberImportModal.js
client/src/Components/Importer/courseCodeMemberImportModal.css
client/src/Components/Search/GenericSearchResults.js
client/src/Components/Search/genericSearchResults.css
client/src/Components/UI/Member/Member.js
client/src/Components/index.js
client/src/Containers/Create/MakeRooms/AddParticipants.js
client/src/Containers/Create/MakeRooms/makeRooms.css
client/src/Containers/Members/Members.js
client/src/Containers/Members/SearchResults.js
client/src/Containers/index.js
client/src/store/actions/courses.js
client/src/utils/hexToRGBA.js
client/src/utils/index.js

Import members into a course via course code.
This gives facilitators the ability to share rosters without having to be facilitators of the collaborative courses.
@Todo: create a stronger association between courses and colors within the course code import modal

Course code import

---

client/src/Containers/Data/withPopulatedRoom.js
client/src/Containers/Workspace/Workspace.js

Clarify when we are updating current members (possible fix to some sync issues)

Separate setting and getting of current members

---

client/src/Containers/Data/withPopulatedRoom.js
client/src/Containers/Workspace/Workspace.js

Reverts mathematicalthinking/vmt#859

Revert "Separate setting and getting of current members"

---

client/src/Containers/Monitoring/MonitoringView.js
client/src/Containers/Monitoring/RoomsMonitor.js
client/src/Containers/Monitoring/monitoringView.css

Reverts mathematicalthinking/vmt#861

Revert "New approach to monitor updates"

---

client/src/Components/Importer/CourseCodeMemberImport.js
client/src/Components/Importer/CourseCodeMemberImportFunctions.js
client/src/Components/Importer/CourseCodeMemberImportModal.js
client/src/Components/Search/GenericSearchResults.js
client/src/Components/UI/ToggleGroup/toggleGroup.css
client/src/Containers/Create/MakeRooms/AddParticipants.js
client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/makeRooms.css
client/src/Containers/Members/Members.js
client/src/Containers/Workspace/Workspace.js
server/sockets.js

When somebody joins a room, for example if they refresh the page, sync who is in control between users based on who the db thinks is in control.

Better handle syncing who is in control on room JOIN events

---

client/src/Components/Importer/ImportModal.js
client/src/Components/UI/Modal/bigModal.css
client/src/Containers/Create/MakeRooms/AddParticipants.js
client/src/Containers/Create/MakeRooms/makeRooms.css

- Expand bigModal width to accomodate a title in AddParticipants ("Add Members")
- Filter out current course in AddParticipants
- AddParticipants -> Course Code search: show courseCode in search results
- AddParticipants setState bug fix

Add participants cleanup

---

client/src/Containers/Course.js

This PR fixes a bug that filtered out / didn't display Course guests.

Display guests in Course Guest List

---

client/src/Containers/Members/Members.js
client/src/store/actions/rooms.js

Fix error where adding a course member to a room sometimes didn't work

Fix room member invite

---

client/src/utils/apiRequests.js
client/src/utils/utilityHooks.js
server/controllers/RoomController.js
server/routes/api.js

This PR provides another strategy for monitoring/course preview retrieval of room information from the DB.  DB queries from the monitor will now return info from only those rooms that have changed since the last query.

More efficient monitoring

---

client/src/utils/utilityHooks.js

Fix hooks for monitoring

---

client/src/Containers/Monitoring/CourseMonitor.js
client/src/Containers/Monitoring/MonitoringView.js
client/src/Containers/Monitoring/RoomsMonitor.js
client/src/utils/utilityHooks.js

This PR adds the new monitoring strategy to CoursePreview

Monitor fixes

---

client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/MakeRooms.js

Make default grouping name the name of the Template

---

client/src/Containers/Course.js
client/src/Layout/CourseRooms/CourseRooms.js
client/src/Layout/SelectableBoxList/SelectableBoxList.js

- Unhide CourseRooms
- Disallow entering archived rooms lobbies
- On archive / unarchive only send archivable / unarchivable ids to the api

Finish unified Course Rooms list

---

client/src/Components/InfoBox/InfoBox.js
client/src/Components/UI/ContentBox/SelectableContentBox.css
client/src/Components/UI/ContentBox/SelectableContentBox.js
client/src/Containers/Course.js
client/src/Layout/CourseRooms/CourseRooms.js
client/src/Layout/CourseRooms/courseRooms.css
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Layout/Dashboard/MainContent/resourceList.css
client/src/Layout/SelectableBoxList/SelectableBoxList.css
client/src/Layout/SelectableBoxList/SelectableBoxList.js

Update styling for MyVMT rooms list Select Actions

Course rooms styling & update rooms list when a new room is created

---

client/src/Containers/RoomLobby.js

RoomLobby > get course id from room instead of params

Fix Room Breadcrumbs

---

client/src/Layout/CourseRooms/courseRooms.css
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/Layout/Dashboard/MainContent/resourceList.css
client/src/Layout/SelectableBoxList/SelectableBoxList.css

Embiggen the Expand/Collapse button, make ResourceList selectActions smart like CourseRooms (cursor: default & less font-width if nothing is selected)

Select actions improvement

---

client/package.json
client/src/Containers/Create/MakeRooms/AssignmentMatrix.js
client/src/Containers/Create/MakeRooms/EditRooms.js
client/src/Containers/Create/MakeRooms/MakeRooms.js
server/routes/api.js

This pr ignores guests within the AssignmentMatrix and MakeRooms which allows for more even distribution of guests during the shuffle process.

Dealing with guests

---

client/src/Containers/Monitoring/RoomsMonitor.js
server/controllers/RoomController.js
server/models/Room.js

Give Room model a dbUpdatedAt field which allows for us to monitor when somebody enters / exits a room while keeping our strategy of not updating lists based on these actions.

Base monitor caching on new dbUpdatedAt field, show aliases in Attendance

---

client/src/Components/CurrentMembers/DisplayTabsCM.js
client/src/Components/index.js
client/src/Containers/Data/withPopulatedRoom.js
client/src/Containers/Workspace/TempWorkspace.js
client/src/Containers/Workspace/Workspace.js
client/src/store/reducers/roomsReducer.js
client/src/utils/controlMachine.js
server/controllers/RoomController.js
server/controllers/TabController.js
server/models/Room.js
server/models/Tab.js
server/sockets.js

This PR includes the work to remove Tab.currentMembers, and update the associated functions to be able to accurately (using from the db) keep track of which currentMembers are in which tab.

Room.currentMembers has a tab

---

client/src/Components/UI/Backdrop/Backdrop.css
client/src/Components/UI/Modal/modal.css
client/src/Containers/Workspace/DropdownTabs.js
client/src/Containers/Workspace/Workspace.js
client/src/Layout/Workspace/workspace.css

- Only show tab# when there's more than one tab. 
- Give Create New Tab a tooltip
- Disable tab dropdown if there's only one tab
- Increase z-index for Modal and Backdrop

Tab list style

---

client/src/Containers/Course.js
client/src/Containers/Members/Members.js
client/src/Containers/RoomLobby.js
client/src/utils/apiRequests.js
server/controllers/RoomController.js
server/controllers/UserController.js
server/routes/api.js

This also also facilitators to download stats for archived course rooms. 
Course and RoomLobby now generate changeRole functions and hand those functions to Members

Give members access to course's archived rooms when they become a course facilitator

---

client/src/Containers/Create/NewResource/NewResource.js
client/src/Containers/Create/NewResource/Step2Copy.js

User can now choose to filter the templates they've created

added filter function

---

client/src/Containers/Stats/statsReducer.js

Reverts mathematicalthinking/vmt#978

Revert "simplify max and min"

---

client/src/Containers/RoomLobby.js
client/src/Containers/Workspace/ActivityWorkspace.js

Fix bug in ActivityWorkshop new tab creation by passing in currentTabId.
Display Desmos Activity links if available.

Edit Template new tab fix, Room Lobby desmosLink

---

client/src/Components/CurrentMembers/DisplayTabsCM.js
client/src/Containers/Workspace/Workspace.js
client/src/utils/controlMachine.js

Fixes a bug on notifications of who's in control when someone switches tabs.

:bug: switching tabs

---

client/src/Containers/Data/withPopulatedRoom.js
server/sockets.js

Proper English & correct variable name

two tiny :bug:

---

client/src/Containers/Create/NewResource/NewResource.js
client/src/Containers/Create/NewResource/Step1.js
client/src/Containers/Create/create.css
server/models/Activity.js

Template search

---

client/src/utils/controlMachine.js

When someone requests control, provide a popup on the user who is currently in control. That user gets to decide whether to immediately release control or to take one more minute.

Popup when someone requests control

---

server/sockets.js

Reverts mathematicalthinking/vmt#1007

Revert "Comment out kill zombies"

---

client/src/Components/Spinner/Spinner.js
client/src/Components/Spinner/spinner.css
client/src/Components/index.js
client/src/Containers/Create/NewResource/Step2Copy.js
client/src/Containers/Create/create.css
client/src/Containers/Monitoring/RoomPreview.js
client/src/Containers/Monitoring/RoomsMonitor.js
client/src/Containers/Monitoring/monitoringView.css

Refactored previous uses of spinner to be a standalone component.

Added a spinner component

---

client/src/Containers/Create/NewResource/Step1.js
client/src/Containers/Create/NewResource/Step2Copy.js

Fix the search functionality in Use Existing Templates

Fix search template

---

client/src/Containers/Create/NewResource/Step2Copy.js
server/controllers/ActivityController.js

TODO: 
* searching should be done on the server so that we search all activities instead of the limited number we get back
* use pagination to include front end functionality like: "Page 1/4", "Next", "Previous", "Go to first", "Go to last"

Remove skip & limit to allow for an iterative deploy approach

---

client/src/Containers/Create/MakeRooms/EditRooms.js

Changing room settings changed in Edit Assignments works and live updates the settings for those rooms.

EditRooms Room settings work & live update rooms

---

client/src/Containers/Create/MakeRooms/MakeRooms.js
client/src/Containers/Create/MakeRooms/SelectAssignments.js
client/src/store/actions/rooms.js
client/src/utils/groupings.js
server/models/Activity.js
server/models/Course.js

Give groupings a settings field in the db & load them in MakeRooms & EditRooms

Thoroughly handle grouping settings

---

client/src/Containers/Workspace/Workspace.js
client/src/utils/utilityHooks.js

Fixed two bugs that were preventing thumbnails from being generated:
- an older bug that prevented screen snapshots from being captured when a student switches DemosActivity screens
- a recent bug that prevented screen snapshots when someone gave up control

Fix thumbnails

---

client/src/Components/Form/TextInput/TextInput.js
client/src/Components/UI/Member/Member.js
client/src/Containers/Members/Members.js
client/src/Containers/Members/members.css
client/src/store/actions/user.js
client/src/utils/apiRequests.js
server/controllers/UserController.js
server/routes/api.js

Only admins have access to this. 
Course Facilitator names cannot be updated.  
- Click the new checkbox on the Members list
- Edit the desired participant name(s)
- Click the red "save" button

Admins can update usernames on the Course Members page

---

client/src/Containers/RoomLobby.js

This uses the same sortParticipants function as the Course container component.

Room members sort

---

client/src/App.js
client/src/Components/GeneralResources.js
client/src/Containers/Replayer/DesActivityMiniReplayer.js
client/src/Containers/Replayer/DesmosMiniReplayer.js
client/src/Containers/Replayer/SharedMiniReplayer.js
client/src/Model/TabTypes.js
server/controllers/RoomController.js

Implements Thumbnails that work from the current state of a Desmos Activity, rather than from screen snapshots.
For now:
- only works for DesmosActivities
- best viewed via Course Preview
Note that this implementation is just for a demo, so no attempt has been made to minimize network traffic.

New Thumbnail approach

---

client/src/App.js
client/src/Components/GeneralResources.js
client/src/Containers/Replayer/DesActivityMiniReplayer.js
client/src/Containers/Replayer/DesmosMiniReplayer.js
client/src/Containers/Replayer/SharedMiniReplayer.js
client/src/Model/TabTypes.js
server/controllers/RoomController.js

Reverts mathematicalthinking/vmt#1082

Revert "Revert "New Thumbnail approach""

---

client/src/Containers/Replayer/DesActivityMiniReplayer.js

reinstate delayed load of activity player

---

client/src/Containers/Activity.js
client/src/Containers/Course.js
client/src/Containers/Create/NewResource/NewResource.js
client/src/Layout/CourseRooms/CourseRooms.js
client/src/Layout/Dashboard/MainContent/ResourceList.js

Now, if you create a room in a template the room will appear in the template's room list.

Fix template standalone room creation

---

server/sockets.js

When two users (A & B) request control at precisely the same time, a weird thing happens:
- A's screen shows that B is in control
- B's screen shows that A is in control
- Other users' screens show that A is in control
This PR attempts a fix by using Redis (which is single threaded) to prevent simultaneous requests, giving control to whichever user Redis decides was first.

Use a lock in redis to handle simultaneous requests for control

---

server/sockets.js

Reverts mathematicalthinking/vmt#1092

Revert "Use a lock in redis to handle simultaneous requests for control"

---

client/src/utils/controlMachine.js
server/sockets.js

avoid control errors: default tab control

---

client/src/Routes/MyVmt.js

Add this hotfix to development.

Fix bad room link

---

client/src/Components/UI/Member/Member.js
client/src/Containers/Members/Members.js
client/src/utils/apiRequests.js
client/src/utils/auth.js
server/routes/admin.js
server/routes/api.js
server/routes/auth.js
server/services/sso.js

This is a test deploy of the new feature to update usernames locally, with MT-SSO, and in Encompass.

Feature to update usernames

---

server/routes/auth.js

Fixes a bug when VMT receives a request to change a username

Fix username change

---

client/src/App.js
client/src/Components/IdleDetector.js
client/src/Components/index.js
client/src/utils/utilityHooks.js

This PR implements an autologout feature. If the user is idle for 30 minutes (i.e., no keystroke, mouse click, or scroll), the user will be automatically logged out. Note that this is a pure client-side implementation that requires the user to keep at least one VMT window/tab open (although not necessarily visible on their screen).

Idle detection

---

client/package.json
client/src/Components/Navigation/Navbar.js
client/src/Containers/Course.js
client/src/Containers/MyVMT.js

This PR implements the following:
- General monitoring is only available from the top navigation bar and only for admins
- Course Preview is available only for facilitators of that course

Restrict monitor and preview

---

client/src/Components/Loading/SimpleLoading.js
client/src/Components/Loading/loading.css
client/src/Components/index.js
client/src/Containers/Monitoring/CourseMonitor.js
client/src/Containers/Workspace/Workspace.js
client/src/utils/dateAndTime.js

* Puts the ALL option at the end of the dropdown
* if the user enters and leaves a room, the course preview will put that room first (because it orders rooms reverse chronologically)
* As rooms are loading, a loading message appears

Adjustments to course preview

---

client/package-lock.json
server/controllers/ActivityController.js
server/controllers/CourseController.js
server/controllers/RoomController.js

* Speed up Community search for Rooms, Templates. and Courses
* Fix some tab type errors in the Admin Dashboard

Update for Community search

---

client/src/Containers/Dashboard.js
client/src/Layout/AdminDashboard/AdminDashboard.js

* Eliminated spurious responses
* Added loading indicator

Cleaned up Dashboard loading

---

client/__tests__/dateAndTime.js
client/__tests__/momenttest.js
client/src/Components/Navigation/HomeNav/HomeNav.js
client/src/Components/Navigation/NavItem/NavItem.js
client/src/Components/Navigation/Navbar.js
client/src/Containers/Activity.js
client/src/Containers/Course.js
client/src/Containers/Monitoring/CourseMonitor.js
client/src/Containers/MyVMT.js
client/src/Layout/CourseRooms/CourseRooms.js
client/src/Layout/Dashboard/MainContent/ResourceList.js
client/src/utils/apiRequests.js
client/src/utils/dateAndTime.js
server/routes/api.js

This PR does the following:
* Changes the label of the Course Preview to 'Monitor'
* Changes the label of the Template Preview to 'Monitor & Review'
* Reintroduces the Monitor to the MyVMT page
* Updates the Course Monitor to show only those course rooms with activity in the past 48 hours. The monitor updates with new room activity and with an updated list of rooms (i.e., rooms with new activity or new rooms) about every 10 seconds.
* Change all myVMT and other lists to default to showing resources updated in the past month.
Still to be done:
* Update Template Monitor & Review, if needed
* Update the myVMT monitor to work the same as Course Monitor except for all rooms accessible by the user

Change preview to monitor

---

client/package.json
client/src/Components/Navigation/Navbar.js
client/src/Containers/Monitoring/AllRoomsMonitor.js
client/src/Containers/Monitoring/MonitoringView.js
client/src/Containers/Monitoring/RecentMonitor.js
client/src/Containers/Monitoring/TemplatePreview.js
client/src/Containers/index.js
client/src/Layout/Dashboard/MainContent/DashboardContent.js
client/src/Routes/MyVmt.js
server/package.json
server/routes/api.js

* Course Monitor now shows rooms updated in past two days plus a total count to inform the user of rooms not shown.
* Template Monitor simplified. Shows all rooms associated with a template.
* myVMT Monitor updated to show only (a) rooms for which the user is a facilitator and (b) rooms updated in the past two days.
* Admin Monitor (appears on top navigation bar) shows the original monitoring functionality (ability to select which rooms to view, whether facilitated or not). Only accessible by Admins.

New monitors

---

client/src/Containers/Monitoring/AdminMonitor.js
client/src/Containers/Monitoring/RecentMonitor.js
client/src/Routes/MyVmt.js

The new Admin Monitor shows all rooms, throughout VMT, that have been updated in the past 48 hours.

New Admin Monitor

---

server/controllers/ActivityController.js
server/controllers/CourseController.js
server/controllers/UserController.js
server/routes/api.js

Adjust to be consistent with rest of codebase

Refactor monitor backend

---

client/src/App.js
client/src/Components/HOC/SocketProvider.js
client/src/store/actions/user.js
server/sockets.js

Reverts mathematicalthinking/vmt#1180

Revert "Fix for some backend errors on forced logout"

---

client/src/Containers/Activity.js
client/src/Containers/Create/NewResource/NewResource.js
client/src/Containers/Create/NewResource/RoomOpts.js
client/src/Containers/Replayer/PyretActivityReplayer.js
client/src/Containers/RoomLobby.js
client/src/Containers/Workspace/PyretActivity.js
client/src/Containers/Workspace/PyretTemplateEditor.js
client/src/Containers/Workspace/Workspace.js
client/src/Model/TabTypes.js
server/controllers/RoomController.js

* Allow Pyret Rooms & Templates to receive published Pyret URLs
* Replayer of a pyret room that was generated by a template begins playback at the template's initial state
* "Referencing" slider only appears for GeoGebra tabs
* Preliminary action descriptions in Pyret rooms for the room data

Pyret-VMT updates

---

client/package.json
client/src/Components/UI/ContentBox/DashboardContentBox.js
client/src/Layout/AdminDashboard/AdminDashboard.js
client/src/Layout/DashboardBoxList/DashboardBoxList.js
server/controllers/UserController.js
server/models/User.js
server/routes/auth.js

Adds a "Last Login" field to user results in the Admin Dashboard.

Timestamp logins & report on admin dashboard

---

client/src/Components/HOC/OauthReturn.js
client/src/utils/auth.js
client/src/utils/index.js
server/app.js
server/routes/auth.js
server/routes/oauth.js

Reverts mathematicalthinking/vmt#1235

Revert "timestamp login via client request"

---

client/package.json
client/src/Containers/Course.js
client/src/Routes/MyVmt.js
client/src/store/reducers/coursesReducer.js
client/src/utils/withPopulatedCourse.js

This PR fixes some bugs:
* When an admin tried to access a course they were not a member of (via Community), there was an error message.
* Archiving sometimes failed because courses don't have full default.

Fix admin course access and archiving

---

client/src/store/actions/user.js
client/src/store/utils.js

Provide clearer error messages on login if at least one of the user's resources is malformed in some way.

Better error messages on login

---

.gitignore
client/jsconfig.json
client/package.json
client/src/Containers/Workspace/GgbGraph.js
client/src/Containers/Workspace/PyretActivity.js
client/src/Containers/Workspace/Workspace.js

This PR has fixes to referencing. One case is still buggy: When a GGB tab is not the first in the room, initial referencing might be off.

Updates to getting coord from GGB applet
